scl file name : collectibles (0a @ 1)

?item block { (12 @ f)


    ?sub-item sub-block { (0a @ 12)

        name : iselon_shard_1 (12 @ 15)

        component sub-sub-block { (1a @ 25)

            component type : PhysicsObject (0a @ 27)
            number : 1(10 @ 36)

            physics object sub-sub-sub-block { (4fa @ 39)

                u0 : 1(08 @ 3b)
                u2 : 0.75 (1d @ 3d)
                u3 : 1500.0 (25 @ 42)
                u4 : 0.0 (2d @ 47)
                u5 : 700.0 (35 @ 4c)
                u6 : 0(38 @ 51)
                u7 : 0.0 (45 @ 53)
			}
		}

        component sub-sub-block { (1a @ 58)

            component type : CollectableItem (0a @ 5a)
            number : 2(10 @ 6b)

            collectable item sub-sub-sub-block { (fb2 @ 6e)

                u0 : 0(08 @ 70)
                u1 : 0(10 @ 72)

                lua chunk sub-sub-sub-sub-block { (1a @ 74)

				}
                name :  (22 @ 76)
                ?model : iselon_shard_1 (2a @ 78)
                u0 : 1(30 @ 88)
			}
		}

        component sub-sub-block { (1a @ 8a)

            component type : ModelTransformController (0a @ 8c)
            number : 3(10 @ a6)

            model transform controller sub-sub-sub-block { (342 @ a9)

                u0 : 101(08 @ ab)
                u2 : 3.1415927410125732 (2d @ ad)
			}
		}

        component sub-sub-block { (1a @ b2)

            component type : Model (0a @ b4)
            number : 101(10 @ bb)

            3D model sub-sub-sub-block { (32a @ be)

                name : item_iselon_shard_1 (0a @ c0)
                u0 : 0.3490658402442932 (15 @ d5)
                u1 : 5.0 (1d @ da)
                u2 : 0.3490658402442932 (25 @ df)

                u3 sub-sub-sub-sub-block { (2a @ e4)

                    w : 0.0 (0d @ e6)
                    x : 0.0 (15 @ eb)
                    y : 0.0 (1d @ f0)
                    z : 1.0 (25 @ f5)
				}

                u4 sub-sub-sub-sub-block { (32 @ fa)

                    x : 0.0 (0d @ fc)
                    y : 0.0 (15 @ 101)
                    z : 0.0 (1d @ 106)
				}
                u5 : 0(38 @ 10b)

                u6 sub-sub-sub-sub-block { (42 @ 10d)

                    w : 1.0 (0d @ 10f)
                    x : 1.0 (15 @ 114)
                    y : 1.0 (1d @ 119)
                    z : 1.0 (25 @ 11e)
				}
			}
		}

        component sub-sub-block { (1a @ 123)

            component type : SimpleGlow (0a @ 125)
            number : 102(10 @ 131)

            simple glow sub-sub-sub-block { (7f2 @ 134)


                u0 sub-sub-sub-sub-block { (0a @ 136)

                    w : 0.3283950686454773 (0d @ 138)
                    x : 0.45822399854660034 (15 @ 13d)
                    y : 0.5160493850708008 (1d @ 142)
                    z : 0.0 (25 @ 147)
				}
                u1 : 40.0 (15 @ 14c)
                u2 : 15(18 @ 151)
                u3 : 15.0 (25 @ 153)
                u4 : 0.15000000596046448 (2d @ 158)
                u5 : 0.800000011920929 (35 @ 15d)

                u6 sub-sub-sub-sub-block { (3a @ 162)

                    y : 0.0 (0d @ 164)
                    z : 10.0 (15 @ 169)
				}
			}
		}

        component sub-sub-block { (1a @ 16e)

            component type : CollisionShape (0a @ 170)
            number : 105(10 @ 180)

            collision shape sub-sub-sub-block { (3c2 @ 183)


                u0 sub-sub-sub-sub-block { (0a @ 185)

                    w : -17.0 (0d @ 187)
                    x : -15.0 (15 @ 18c)
                    y : 34.0 (1d @ 191)
                    z : 45.0 (25 @ 196)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 19c)

                u1 : 1(18 @ 19e)
                w : -40.0 (35 @ 1a0)
                x : 40.0 (3d @ 1a5)
                y : 3(40 @ 1aa)
                z : 1(58 @ 1ac)
			}
		}

        position sub-sub-block { (22 @ 1ae)

            x position : 0.0 (0d @ 1b0)
            y position : 0.0 (15 @ 1b5)
		}
        z position : 0.0 (2d @ 1ba)
        rotation : 0.0 (35 @ 1bf)
        scale : 1.0 (3d @ 1c4)

        u0 sub-sub-block { (42 @ 1c9)

            w : -40.0 (0d @ 1cb)
            x : -40.0 (15 @ 1d0)
            y : 80.0 (1d @ 1d5)
            z : 80.0 (25 @ 1da)
		}
        hidden : 0(48 @ 1df)
	}
    u0 : 1.0 (15 @ 1e1)
}

?item block { (12 @ 1e6)


    ?sub-item sub-block { (0a @ 1e9)

        name : iselon_shard_2 (12 @ 1ec)

        component sub-sub-block { (1a @ 1fc)

            component type : PhysicsObject (0a @ 1fe)
            number : 1(10 @ 20d)

            physics object sub-sub-sub-block { (4fa @ 210)

                u0 : 1(08 @ 212)
                u2 : 0.75 (1d @ 214)
                u3 : 1500.0 (25 @ 219)
                u4 : 0.0 (2d @ 21e)
                u5 : 700.0 (35 @ 223)
                u6 : 0(38 @ 228)
                u7 : 0.0 (45 @ 22a)
			}
		}

        component sub-sub-block { (1a @ 22f)

            component type : CollectableItem (0a @ 231)
            number : 2(10 @ 242)

            collectable item sub-sub-sub-block { (fb2 @ 245)

                u0 : 0(08 @ 247)
                u1 : 0(10 @ 249)

                lua chunk sub-sub-sub-sub-block { (1a @ 24b)

				}
                name :  (22 @ 24d)
                ?model : iselon_shard_2 (2a @ 24f)
                u0 : 1(30 @ 25f)
			}
		}

        component sub-sub-block { (1a @ 261)

            component type : ModelTransformController (0a @ 263)
            number : 3(10 @ 27d)

            model transform controller sub-sub-sub-block { (342 @ 280)

                u0 : 101(08 @ 282)
                u2 : 3.1415927410125732 (2d @ 284)
			}
		}

        component sub-sub-block { (1a @ 289)

            component type : Model (0a @ 28b)
            number : 101(10 @ 292)

            3D model sub-sub-sub-block { (32a @ 295)

                name : item_iselon_shard_2 (0a @ 297)
                u0 : 0.3490658402442932 (15 @ 2ac)
                u1 : 5.0 (1d @ 2b1)
                u2 : 0.3490658402442932 (25 @ 2b6)

                u3 sub-sub-sub-sub-block { (2a @ 2bb)

                    w : 0.0 (0d @ 2bd)
                    x : 0.0 (15 @ 2c2)
                    y : 0.0 (1d @ 2c7)
                    z : 1.0 (25 @ 2cc)
				}

                u4 sub-sub-sub-sub-block { (32 @ 2d1)

                    x : 0.0 (0d @ 2d3)
                    y : 0.0 (15 @ 2d8)
                    z : 0.0 (1d @ 2dd)
				}
                u5 : 0(38 @ 2e2)

                u6 sub-sub-sub-sub-block { (42 @ 2e4)

                    w : 1.0 (0d @ 2e6)
                    x : 1.0 (15 @ 2eb)
                    y : 1.0 (1d @ 2f0)
                    z : 1.0 (25 @ 2f5)
				}
			}
		}

        component sub-sub-block { (1a @ 2fa)

            component type : SimpleGlow (0a @ 2fc)
            number : 102(10 @ 308)

            simple glow sub-sub-sub-block { (7f2 @ 30b)


                u0 sub-sub-sub-sub-block { (0a @ 30d)

                    w : 0.3283950686454773 (0d @ 30f)
                    x : 0.45822399854660034 (15 @ 314)
                    y : 0.5160493850708008 (1d @ 319)
                    z : 0.0 (25 @ 31e)
				}
                u1 : 40.0 (15 @ 323)
                u2 : 15(18 @ 328)
                u3 : 15.0 (25 @ 32a)
                u4 : 0.15000000596046448 (2d @ 32f)
                u5 : 0.800000011920929 (35 @ 334)

                u6 sub-sub-sub-sub-block { (3a @ 339)

                    y : 0.0 (0d @ 33b)
                    z : 10.0 (15 @ 340)
				}
			}
		}

        component sub-sub-block { (1a @ 345)

            component type : CollisionShape (0a @ 347)
            number : 105(10 @ 357)

            collision shape sub-sub-sub-block { (3c2 @ 35a)


                u0 sub-sub-sub-sub-block { (0a @ 35c)

                    w : -17.0 (0d @ 35e)
                    x : -15.0 (15 @ 363)
                    y : 34.0 (1d @ 368)
                    z : 45.0 (25 @ 36d)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 373)

                u1 : 1(18 @ 375)
                w : -40.0 (35 @ 377)
                x : 40.0 (3d @ 37c)
                y : 3(40 @ 381)
                z : 1(58 @ 383)
			}
		}

        position sub-sub-block { (22 @ 385)

            x position : 0.0 (0d @ 387)
            y position : 0.0 (15 @ 38c)
		}
        z position : 0.0 (2d @ 391)
        rotation : 0.0 (35 @ 396)
        scale : 1.0 (3d @ 39b)

        u0 sub-sub-block { (42 @ 3a0)

            w : -40.0 (0d @ 3a2)
            x : -40.0 (15 @ 3a7)
            y : 80.0 (1d @ 3ac)
            z : 80.0 (25 @ 3b1)
		}
        hidden : 0(48 @ 3b6)
	}
    u0 : 1.0 (15 @ 3b8)
}

?item block { (12 @ 3bd)


    ?sub-item sub-block { (0a @ 3c0)

        name : iselon_shard_3 (12 @ 3c3)

        component sub-sub-block { (1a @ 3d3)

            component type : PhysicsObject (0a @ 3d5)
            number : 1(10 @ 3e4)

            physics object sub-sub-sub-block { (4fa @ 3e7)

                u0 : 1(08 @ 3e9)
                u2 : 0.75 (1d @ 3eb)
                u3 : 1500.0 (25 @ 3f0)
                u4 : 0.0 (2d @ 3f5)
                u5 : 700.0 (35 @ 3fa)
                u6 : 0(38 @ 3ff)
                u7 : 0.0 (45 @ 401)
			}
		}

        component sub-sub-block { (1a @ 406)

            component type : CollectableItem (0a @ 408)
            number : 2(10 @ 419)

            collectable item sub-sub-sub-block { (fb2 @ 41c)

                u0 : 0(08 @ 41e)
                u1 : 0(10 @ 420)

                lua chunk sub-sub-sub-sub-block { (1a @ 422)

				}
                name :  (22 @ 424)
                ?model : iselon_shard_3 (2a @ 426)
                u0 : 1(30 @ 436)
			}
		}

        component sub-sub-block { (1a @ 438)

            component type : ModelTransformController (0a @ 43a)
            number : 3(10 @ 454)

            model transform controller sub-sub-sub-block { (342 @ 457)

                u0 : 101(08 @ 459)
                u2 : 3.1415927410125732 (2d @ 45b)
			}
		}

        component sub-sub-block { (1a @ 460)

            component type : Model (0a @ 462)
            number : 101(10 @ 469)

            3D model sub-sub-sub-block { (32a @ 46c)

                name : item_iselon_shard_3 (0a @ 46e)
                u0 : 0.3490658402442932 (15 @ 483)
                u1 : 5.0 (1d @ 488)
                u2 : 0.3490658402442932 (25 @ 48d)

                u3 sub-sub-sub-sub-block { (2a @ 492)

                    w : 0.0 (0d @ 494)
                    x : 0.0 (15 @ 499)
                    y : 0.0 (1d @ 49e)
                    z : 1.0 (25 @ 4a3)
				}

                u4 sub-sub-sub-sub-block { (32 @ 4a8)

                    x : 0.0 (0d @ 4aa)
                    y : 0.0 (15 @ 4af)
                    z : 0.0 (1d @ 4b4)
				}
                u5 : 0(38 @ 4b9)

                u6 sub-sub-sub-sub-block { (42 @ 4bb)

                    w : 1.0 (0d @ 4bd)
                    x : 1.0 (15 @ 4c2)
                    y : 1.0 (1d @ 4c7)
                    z : 1.0 (25 @ 4cc)
				}
			}
		}

        component sub-sub-block { (1a @ 4d1)

            component type : SimpleGlow (0a @ 4d3)
            number : 102(10 @ 4df)

            simple glow sub-sub-sub-block { (7f2 @ 4e2)


                u0 sub-sub-sub-sub-block { (0a @ 4e4)

                    w : 0.3283950686454773 (0d @ 4e6)
                    x : 0.45822399854660034 (15 @ 4eb)
                    y : 0.5160493850708008 (1d @ 4f0)
                    z : 0.0 (25 @ 4f5)
				}
                u1 : 40.0 (15 @ 4fa)
                u2 : 15(18 @ 4ff)
                u3 : 15.0 (25 @ 501)
                u4 : 0.15000000596046448 (2d @ 506)
                u5 : 0.800000011920929 (35 @ 50b)

                u6 sub-sub-sub-sub-block { (3a @ 510)

                    y : 0.0 (0d @ 512)
                    z : 10.0 (15 @ 517)
				}
			}
		}

        component sub-sub-block { (1a @ 51c)

            component type : CollisionShape (0a @ 51e)
            number : 105(10 @ 52e)

            collision shape sub-sub-sub-block { (3c2 @ 531)


                u0 sub-sub-sub-sub-block { (0a @ 533)

                    w : -17.0 (0d @ 535)
                    x : -15.0 (15 @ 53a)
                    y : 34.0 (1d @ 53f)
                    z : 45.0 (25 @ 544)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 54a)

                u1 : 1(18 @ 54c)
                w : -40.0 (35 @ 54e)
                x : 40.0 (3d @ 553)
                y : 3(40 @ 558)
                z : 1(58 @ 55a)
			}
		}

        position sub-sub-block { (22 @ 55c)

            x position : 0.0 (0d @ 55e)
            y position : 0.0 (15 @ 563)
		}
        z position : 0.0 (2d @ 568)
        rotation : 0.0 (35 @ 56d)
        scale : 1.0 (3d @ 572)

        u0 sub-sub-block { (42 @ 577)

            w : -40.0 (0d @ 579)
            x : -40.0 (15 @ 57e)
            y : 80.0 (1d @ 583)
            z : 80.0 (25 @ 588)
		}
        hidden : 0(48 @ 58d)
	}
    u0 : 1.0 (15 @ 58f)
}

?item block { (12 @ 594)


    ?sub-item sub-block { (0a @ 597)

        name : iselon_shard_4 (12 @ 59a)

        component sub-sub-block { (1a @ 5aa)

            component type : PhysicsObject (0a @ 5ac)
            number : 1(10 @ 5bb)

            physics object sub-sub-sub-block { (4fa @ 5be)

                u0 : 1(08 @ 5c0)
                u2 : 0.75 (1d @ 5c2)
                u3 : 1500.0 (25 @ 5c7)
                u4 : 0.0 (2d @ 5cc)
                u5 : 700.0 (35 @ 5d1)
                u6 : 0(38 @ 5d6)
                u7 : 0.0 (45 @ 5d8)
			}
		}

        component sub-sub-block { (1a @ 5dd)

            component type : CollectableItem (0a @ 5df)
            number : 2(10 @ 5f0)

            collectable item sub-sub-sub-block { (fb2 @ 5f3)

                u0 : 0(08 @ 5f5)
                u1 : 0(10 @ 5f7)

                lua chunk sub-sub-sub-sub-block { (1a @ 5f9)

				}
                name :  (22 @ 5fb)
                ?model : iselon_shard_4 (2a @ 5fd)
                u0 : 1(30 @ 60d)
			}
		}

        component sub-sub-block { (1a @ 60f)

            component type : ModelTransformController (0a @ 611)
            number : 3(10 @ 62b)

            model transform controller sub-sub-sub-block { (342 @ 62e)

                u0 : 101(08 @ 630)
                u2 : 3.1415927410125732 (2d @ 632)
			}
		}

        component sub-sub-block { (1a @ 637)

            component type : Model (0a @ 639)
            number : 101(10 @ 640)

            3D model sub-sub-sub-block { (32a @ 643)

                name : item_iselon_shard_4 (0a @ 645)
                u0 : 0.3490658402442932 (15 @ 65a)
                u1 : 5.0 (1d @ 65f)
                u2 : 0.3490658402442932 (25 @ 664)

                u3 sub-sub-sub-sub-block { (2a @ 669)

                    w : 0.0 (0d @ 66b)
                    x : 0.0 (15 @ 670)
                    y : 0.0 (1d @ 675)
                    z : 1.0 (25 @ 67a)
				}

                u4 sub-sub-sub-sub-block { (32 @ 67f)

                    x : 0.0 (0d @ 681)
                    y : 0.0 (15 @ 686)
                    z : 0.0 (1d @ 68b)
				}
                u5 : 0(38 @ 690)

                u6 sub-sub-sub-sub-block { (42 @ 692)

                    w : 1.0 (0d @ 694)
                    x : 1.0 (15 @ 699)
                    y : 1.0 (1d @ 69e)
                    z : 1.0 (25 @ 6a3)
				}
			}
		}

        component sub-sub-block { (1a @ 6a8)

            component type : SimpleGlow (0a @ 6aa)
            number : 102(10 @ 6b6)

            simple glow sub-sub-sub-block { (7f2 @ 6b9)


                u0 sub-sub-sub-sub-block { (0a @ 6bb)

                    w : 0.3283950686454773 (0d @ 6bd)
                    x : 0.45822399854660034 (15 @ 6c2)
                    y : 0.5160493850708008 (1d @ 6c7)
                    z : 0.0 (25 @ 6cc)
				}
                u1 : 40.0 (15 @ 6d1)
                u2 : 15(18 @ 6d6)
                u3 : 15.0 (25 @ 6d8)
                u4 : 0.15000000596046448 (2d @ 6dd)
                u5 : 0.800000011920929 (35 @ 6e2)

                u6 sub-sub-sub-sub-block { (3a @ 6e7)

                    y : 0.0 (0d @ 6e9)
                    z : 10.0 (15 @ 6ee)
				}
			}
		}

        component sub-sub-block { (1a @ 6f3)

            component type : CollisionShape (0a @ 6f5)
            number : 105(10 @ 705)

            collision shape sub-sub-sub-block { (3c2 @ 708)


                u0 sub-sub-sub-sub-block { (0a @ 70a)

                    w : -17.0 (0d @ 70c)
                    x : -15.0 (15 @ 711)
                    y : 34.0 (1d @ 716)
                    z : 45.0 (25 @ 71b)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 721)

                u1 : 1(18 @ 723)
                w : -40.0 (35 @ 725)
                x : 40.0 (3d @ 72a)
                y : 3(40 @ 72f)
                z : 1(58 @ 731)
			}
		}

        position sub-sub-block { (22 @ 733)

            x position : 0.0 (0d @ 735)
            y position : 0.0 (15 @ 73a)
		}
        z position : 0.0 (2d @ 73f)
        rotation : 0.0 (35 @ 744)
        scale : 1.0 (3d @ 749)

        u0 sub-sub-block { (42 @ 74e)

            w : -40.0 (0d @ 750)
            x : -40.0 (15 @ 755)
            y : 80.0 (1d @ 75a)
            z : 80.0 (25 @ 75f)
		}
        hidden : 0(48 @ 764)
	}
    u0 : 1.0 (15 @ 766)
}

?item block { (12 @ 76b)


    ?sub-item sub-block { (0a @ 76e)

        name : item_brasssword (12 @ 771)

        component sub-sub-block { (1a @ 782)

            component type : PhysicsObject (0a @ 784)
            number : 1(10 @ 793)

            physics object sub-sub-sub-block { (4fa @ 796)

                u0 : 1(08 @ 798)
                u2 : 0.5 (1d @ 79a)
                u3 : 1500.0 (25 @ 79f)
                u4 : 0.0 (2d @ 7a4)
                u5 : 700.0 (35 @ 7a9)
                u6 : 0(38 @ 7ae)
                u7 : 0.0 (45 @ 7b0)
			}
		}

        component sub-sub-block { (1a @ 7b5)

            component type : CollectableItem (0a @ 7b7)
            number : 2(10 @ 7c8)

            collectable item sub-sub-sub-block { (fb2 @ 7cb)

                u0 : 0(08 @ 7cd)
                u1 : 0(10 @ 7cf)

                lua chunk sub-sub-sub-sub-block { (1a @ 7d1)

				}
                name :  (22 @ 7d3)
                ?model : brasssword (2a @ 7d5)
                u0 : 1(30 @ 7e1)
			}
		}

        component sub-sub-block { (1a @ 7e3)

            component type : ModelTransformController (0a @ 7e5)
            number : 3(10 @ 7ff)

            model transform controller sub-sub-sub-block { (342 @ 802)

                u0 : 101(08 @ 804)
                u2 : 3.1415927410125732 (2d @ 806)
			}
		}

        component sub-sub-block { (1a @ 80b)

            component type : Model (0a @ 80d)
            number : 101(10 @ 814)

            3D model sub-sub-sub-block { (32a @ 817)

                name : weapon_ironsword (0a @ 819)
                u0 : 0.7853981852531433 (15 @ 82b)
                u1 : 1.0 (1d @ 830)
                u2 : 1.5707963705062866 (25 @ 835)

                u3 sub-sub-sub-sub-block { (2a @ 83a)

                    w : 0.0 (0d @ 83c)
                    x : 0.0 (15 @ 841)
                    y : 0.0 (1d @ 846)
                    z : 1.0 (25 @ 84b)
				}

                u4 sub-sub-sub-sub-block { (32 @ 850)

                    x : 15.0 (0d @ 852)
                    y : 0.0 (15 @ 857)
                    z : 0.0 (1d @ 85c)
				}
                u5 : 0(38 @ 861)

                u6 sub-sub-sub-sub-block { (42 @ 863)

                    w : 1.0 (0d @ 865)
                    x : 0.644444465637207 (15 @ 86a)
                    y : 0.42222222685813904 (1d @ 86f)
                    z : 1.0 (25 @ 874)
				}
			}
		}

        component sub-sub-block { (1a @ 879)

            component type : SimpleGlow (0a @ 87b)
            number : 102(10 @ 887)

            simple glow sub-sub-sub-block { (7f2 @ 88a)


                u0 sub-sub-sub-sub-block { (0a @ 88c)

                    w : 0.12263374030590057 (0d @ 88e)
                    x : 0.18696410953998566 (15 @ 893)
                    y : 0.23292176425457 (1d @ 898)
                    z : 0.0 (25 @ 89d)
				}
                u1 : 25.0 (15 @ 8a2)
                u2 : 15(18 @ 8a7)
                u3 : 15.0 (25 @ 8a9)
                u4 : 0.15000000596046448 (2d @ 8ae)
                u5 : 0.800000011920929 (35 @ 8b3)

                u6 sub-sub-sub-sub-block { (3a @ 8b8)

                    y : 0.0 (0d @ 8ba)
                    z : 15.0 (15 @ 8bf)
				}
			}
		}

        component sub-sub-block { (1a @ 8c4)

            component type : CollisionShape (0a @ 8c6)
            number : 105(10 @ 8d6)

            collision shape sub-sub-sub-block { (3c2 @ 8d9)


                u0 sub-sub-sub-sub-block { (0a @ 8db)

                    w : -15.0 (0d @ 8dd)
                    x : -8.0 (15 @ 8e2)
                    y : 30.0 (1d @ 8e7)
                    z : 38.0 (25 @ 8ec)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 8f2)

                u1 : 1(18 @ 8f4)
                w : -40.0 (35 @ 8f6)
                x : 40.0 (3d @ 8fb)
                y : 3(40 @ 900)
                z : 1(58 @ 902)
			}
		}

        position sub-sub-block { (22 @ 904)

            x position : 0.0 (0d @ 906)
            y position : 0.0 (15 @ 90b)
		}
        z position : 0.0 (2d @ 910)
        rotation : 0.0 (35 @ 915)
        scale : 1.0 (3d @ 91a)

        u0 sub-sub-block { (42 @ 91f)

            w : -25.0 (0d @ 921)
            x : -25.0 (15 @ 926)
            y : 50.0 (1d @ 92b)
            z : 55.0 (25 @ 930)
		}
        hidden : 0(48 @ 935)
	}
    u0 : 1.0 (15 @ 937)
}

?item block { (12 @ 93c)


    ?sub-item sub-block { (0a @ 93f)

        name : item_broadsword (12 @ 942)

        component sub-sub-block { (1a @ 953)

            component type : PhysicsObject (0a @ 955)
            number : 1(10 @ 964)

            physics object sub-sub-sub-block { (4fa @ 967)

                u0 : 1(08 @ 969)
                u2 : 0.5 (1d @ 96b)
                u3 : 1500.0 (25 @ 970)
                u4 : 0.0 (2d @ 975)
                u5 : 700.0 (35 @ 97a)
                u6 : 0(38 @ 97f)
                u7 : 0.0 (45 @ 981)
			}
		}

        component sub-sub-block { (1a @ 986)

            component type : CollectableItem (0a @ 988)
            number : 2(10 @ 999)

            collectable item sub-sub-sub-block { (fb2 @ 99c)

                u0 : 0(08 @ 99e)
                u1 : 0(10 @ 9a0)

                lua chunk sub-sub-sub-sub-block { (1a @ 9a2)

				}
                name :  (22 @ 9a4)
                ?model : broadsword (2a @ 9a6)
                u0 : 1(30 @ 9b2)
			}
		}

        component sub-sub-block { (1a @ 9b4)

            component type : ModelTransformController (0a @ 9b6)
            number : 3(10 @ 9d0)

            model transform controller sub-sub-sub-block { (342 @ 9d3)

                u0 : 101(08 @ 9d5)
                u2 : 3.1415927410125732 (2d @ 9d7)
			}
		}

        component sub-sub-block { (1a @ 9dc)

            component type : Model (0a @ 9de)
            number : 101(10 @ 9e5)

            3D model sub-sub-sub-block { (32a @ 9e8)

                name : weapon_broadsword (0a @ 9ea)
                u0 : 0.7853981852531433 (15 @ 9fd)
                u1 : 1.0 (1d @ a02)
                u2 : 1.5707963705062866 (25 @ a07)

                u3 sub-sub-sub-sub-block { (2a @ a0c)

                    w : 0.0 (0d @ a0e)
                    x : 0.0 (15 @ a13)
                    y : 0.0 (1d @ a18)
                    z : 1.0 (25 @ a1d)
				}

                u4 sub-sub-sub-sub-block { (32 @ a22)

                    x : 10.0 (0d @ a24)
                    y : -7.0 (15 @ a29)
                    z : 0.0 (1d @ a2e)
				}
                u5 : 0(38 @ a33)

                u6 sub-sub-sub-sub-block { (42 @ a35)

                    w : 1.0 (0d @ a37)
                    x : 1.0 (15 @ a3c)
                    y : 1.0 (1d @ a41)
                    z : 1.0 (25 @ a46)
				}
			}
		}

        component sub-sub-block { (1a @ a4b)

            component type : SimpleGlow (0a @ a4d)
            number : 102(10 @ a59)

            simple glow sub-sub-sub-block { (7f2 @ a5c)


                u0 sub-sub-sub-sub-block { (0a @ a5e)

                    w : 0.12263374030590057 (0d @ a60)
                    x : 0.18696410953998566 (15 @ a65)
                    y : 0.23292176425457 (1d @ a6a)
                    z : 0.0 (25 @ a6f)
				}
                u1 : 25.0 (15 @ a74)
                u2 : 15(18 @ a79)
                u3 : 15.0 (25 @ a7b)
                u4 : 0.15000000596046448 (2d @ a80)
                u5 : 0.800000011920929 (35 @ a85)

                u6 sub-sub-sub-sub-block { (3a @ a8a)

                    y : 0.0 (0d @ a8c)
                    z : 15.0 (15 @ a91)
				}
			}
		}

        component sub-sub-block { (1a @ a96)

            component type : CollisionShape (0a @ a98)
            number : 105(10 @ aa8)

            collision shape sub-sub-sub-block { (3c2 @ aab)


                u0 sub-sub-sub-sub-block { (0a @ aad)

                    w : -15.0 (0d @ aaf)
                    x : -8.0 (15 @ ab4)
                    y : 30.0 (1d @ ab9)
                    z : 38.0 (25 @ abe)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ ac4)

                u1 : 1(18 @ ac6)
                w : -40.0 (35 @ ac8)
                x : 40.0 (3d @ acd)
                y : 3(40 @ ad2)
                z : 1(58 @ ad4)
			}
		}

        position sub-sub-block { (22 @ ad6)

            x position : 0.0 (0d @ ad8)
            y position : 0.0 (15 @ add)
		}
        z position : 0.0 (2d @ ae2)
        rotation : 0.0 (35 @ ae7)
        scale : 1.0 (3d @ aec)

        u0 sub-sub-block { (42 @ af1)

            w : -25.0 (0d @ af3)
            x : -25.0 (15 @ af8)
            y : 50.0 (1d @ afd)
            z : 55.0 (25 @ b02)
		}
        hidden : 0(48 @ b07)
	}
    u0 : 1.0 (15 @ b09)
}

?item block { (12 @ b0e)


    ?sub-item sub-block { (0a @ b11)

        name : item_firetrinket (12 @ b14)

        component sub-sub-block { (1a @ b26)

            component type : PhysicsObject (0a @ b28)
            number : 1(10 @ b37)

            physics object sub-sub-sub-block { (4fa @ b3a)

                u0 : 1(08 @ b3c)
                u3 : 1500.0 (25 @ b3e)
                u4 : 0.0 (2d @ b43)
                u5 : 700.0 (35 @ b48)
                u6 : 0(38 @ b4d)
                u7 : 0.0 (45 @ b4f)
			}
		}

        component sub-sub-block { (1a @ b54)

            component type : CollectableItem (0a @ b56)
            number : 2(10 @ b67)

            collectable item sub-sub-sub-block { (fb2 @ b6a)

                u0 : 0(08 @ b6c)
                u1 : 0(10 @ b6e)

                lua chunk sub-sub-sub-sub-block { (1a @ b70)

				}
                name :  (22 @ b72)
                ?model : firetrinket (2a @ b74)
                u0 : 1(30 @ b81)
			}
		}

        component sub-sub-block { (1a @ b83)

            component type : ModelTransformController (0a @ b85)
            number : 3(10 @ b9f)

            model transform controller sub-sub-sub-block { (342 @ ba2)

                u0 : 101(08 @ ba4)
                u2 : 3.1415927410125732 (2d @ ba6)
			}
		}

        component sub-sub-block { (1a @ bab)

            component type : Model (0a @ bad)
            number : 101(10 @ bb4)

            3D model sub-sub-sub-block { (32a @ bb7)

                name : item_firetrinket (0a @ bb9)
                u0 : 0.0 (15 @ bcb)
                u1 : 5.0 (1d @ bd0)
                u2 : 0.0 (25 @ bd5)

                u3 sub-sub-sub-sub-block { (2a @ bda)

                    w : 0.0 (0d @ bdc)
                    x : 0.0 (15 @ be1)
                    y : 0.0 (1d @ be6)
                    z : 1.0 (25 @ beb)
				}

                u4 sub-sub-sub-sub-block { (32 @ bf0)

                    x : 0.0 (0d @ bf2)
                    y : -15.0 (15 @ bf7)
                    z : 0.0 (1d @ bfc)
				}
                u5 : 0(38 @ c01)

                u6 sub-sub-sub-sub-block { (42 @ c03)

                    w : 1.0 (0d @ c05)
                    x : 1.0 (15 @ c0a)
                    y : 1.0 (1d @ c0f)
                    z : 1.0 (25 @ c14)
				}
			}
		}

        component sub-sub-block { (1a @ c19)

            component type : SimpleGlow (0a @ c1b)
            number : 102(10 @ c27)

            simple glow sub-sub-sub-block { (7f2 @ c2a)


                u0 sub-sub-sub-sub-block { (0a @ c2c)

                    w : 1.0 (0d @ c2e)
                    x : 0.0 (15 @ c33)
                    y : 0.0 (1d @ c38)
                    z : 0.4777778089046478 (25 @ c3d)
				}
                u1 : 20.0 (15 @ c42)
                u2 : 16(18 @ c47)
                u3 : 15.0 (25 @ c49)
                u4 : 0.15000000596046448 (2d @ c4e)
                u5 : 1.2000000476837158 (35 @ c53)

                u6 sub-sub-sub-sub-block { (3a @ c58)

                    y : 0.0 (0d @ c5a)
                    z : 14.0 (15 @ c5f)
				}
			}
		}

        component sub-sub-block { (1a @ c64)

            component type : CollisionShape (0a @ c66)
            number : 105(10 @ c76)

            collision shape sub-sub-sub-block { (3c2 @ c79)


                u0 sub-sub-sub-sub-block { (0a @ c7b)

                    w : -5.0 (0d @ c7d)
                    x : 0.0 (15 @ c82)
                    y : 10.0 (1d @ c87)
                    z : 30.0 (25 @ c8c)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ c92)

                u1 : 1(18 @ c94)
                w : -40.0 (35 @ c96)
                x : 40.0 (3d @ c9b)
                y : 3(40 @ ca0)
                z : 1(58 @ ca2)
			}
		}

        position sub-sub-block { (22 @ ca4)

            x position : 0.0 (0d @ ca6)
            y position : 0.0 (15 @ cab)
		}
        z position : 0.0 (2d @ cb0)
        rotation : 0.0 (35 @ cb5)
        scale : 1.0 (3d @ cba)

        u0 sub-sub-block { (42 @ cbf)

            w : -20.0 (0d @ cc1)
            x : -20.0 (15 @ cc6)
            y : 40.0 (1d @ ccb)
            z : 50.0 (25 @ cd0)
		}
        hidden : 0(48 @ cd5)
	}
    u0 : 1.0 (15 @ cd7)
}

?item block { (12 @ cdc)


    ?sub-item sub-block { (0a @ cdf)

        name : item_healingpotion (12 @ ce2)

        component sub-sub-block { (1a @ cf6)

            component type : PhysicsObject (0a @ cf8)
            number : 1(10 @ d07)

            physics object sub-sub-sub-block { (4fa @ d0a)

                u0 : 1(08 @ d0c)
                u3 : 1500.0 (25 @ d0e)
                u4 : 0.0 (2d @ d13)
                u5 : 700.0 (35 @ d18)
                u6 : 0(38 @ d1d)
                u7 : 0.0 (45 @ d1f)
			}
		}

        component sub-sub-block { (1a @ d24)

            component type : ModelTransformController (0a @ d26)
            number : 2(10 @ d40)

            model transform controller sub-sub-sub-block { (342 @ d43)

                u0 : 101(08 @ d45)
                u2 : 3.1415927410125732 (2d @ d47)
			}
		}

        component sub-sub-block { (1a @ d4c)

            component type : TransformController (0a @ d4e)
            number : 3(10 @ d63)
		}

        component sub-sub-block { (1a @ d65)

            component type : Model (0a @ d67)
            number : 101(10 @ d6e)

            3D model sub-sub-sub-block { (32a @ d71)

                name : healthbottlebig (0a @ d73)
                u0 : 0.0 (15 @ d84)
                u1 : 5.0 (1d @ d89)
                u2 : 0.0 (25 @ d8e)

                u3 sub-sub-sub-sub-block { (2a @ d93)

                    w : 0.0 (0d @ d95)
                    x : 0.0 (15 @ d9a)
                    y : 0.0 (1d @ d9f)
                    z : 1.0 (25 @ da4)
				}

                u4 sub-sub-sub-sub-block { (32 @ da9)

                    x : 0.0 (0d @ dab)
                    y : -12.0 (15 @ db0)
                    z : 0.0 (1d @ db5)
				}
                u5 : 0(38 @ dba)

                u6 sub-sub-sub-sub-block { (42 @ dbc)

                    w : 1.0 (0d @ dbe)
                    x : 1.0 (15 @ dc3)
                    y : 1.0 (1d @ dc8)
                    z : 1.0 (25 @ dcd)
				}
			}
		}

        component sub-sub-block { (1a @ dd2)

            component type : SimpleGlow (0a @ dd4)
            number : 102(10 @ de0)

            simple glow sub-sub-sub-block { (7f2 @ de3)


                u0 sub-sub-sub-sub-block { (0a @ de5)

                    w : 0.6222222447395325 (0d @ de7)
                    x : 0.0 (15 @ dec)
                    y : 2.8610230629055877e-07 (1d @ df1)
                    z : 0.20000000298023224 (25 @ df6)
				}
                u1 : 20.0 (15 @ dfb)
                u2 : 10(18 @ e00)
                u3 : 5.0 (25 @ e02)
                u4 : 0.15000000596046448 (2d @ e07)
                u5 : 0.800000011920929 (35 @ e0c)

                u6 sub-sub-sub-sub-block { (3a @ e11)

                    y : 0.0 (0d @ e13)
                    z : 9.0 (15 @ e18)
				}
			}
		}

        component sub-sub-block { (1a @ e1d)

            component type : CollisionShape (0a @ e1f)
            number : 104(10 @ e2f)

            collision shape sub-sub-sub-block { (3c2 @ e32)


                u0 sub-sub-sub-sub-block { (0a @ e34)

                    w : -12.0 (0d @ e36)
                    x : 0.0 (15 @ e3b)
                    y : 24.0 (1d @ e40)
                    z : 24.0 (25 @ e45)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ e4b)

                u1 : 1(18 @ e4d)
                w : -15.0 (35 @ e4f)
                x : 15.0 (3d @ e54)
                y : 3(40 @ e59)
                z : 1(58 @ e5b)
			}
		}

        component sub-sub-block { (1a @ e5d)

            component type : CollectableItem (0a @ e5f)
            number : 107(10 @ e70)

            collectable item sub-sub-sub-block { (fb2 @ e73)

                u0 : 0(08 @ e75)
                u1 : 0(10 @ e77)

                lua chunk sub-sub-sub-sub-block { (1a @ e79)

				}
                name :  (22 @ e7b)
                ?model : healingpotion (2a @ e7d)
                u0 : 1(30 @ e8c)
			}
		}

        position sub-sub-block { (22 @ e8e)

            x position : 0.0 (0d @ e90)
            y position : 0.0 (15 @ e95)
		}
        z position : 0.0 (2d @ e9a)
        rotation : 0.0 (35 @ e9f)
        scale : 1.0 (3d @ ea4)

        u0 sub-sub-block { (42 @ ea9)

            w : -20.0 (0d @ eab)
            x : -20.0 (15 @ eb0)
            y : 40.0 (1d @ eb5)
            z : 44.0 (25 @ eba)
		}
        hidden : 0(48 @ ebf)
	}
    u0 : 1.0 (15 @ ec1)
}

?item block { (12 @ ec6)


    ?sub-item sub-block { (0a @ ec9)

        name : item_icetrinket (12 @ ecc)

        component sub-sub-block { (1a @ edd)

            component type : PhysicsObject (0a @ edf)
            number : 1(10 @ eee)

            physics object sub-sub-sub-block { (4fa @ ef1)

                u0 : 1(08 @ ef3)
                u3 : 1500.0 (25 @ ef5)
                u4 : 0.0 (2d @ efa)
                u5 : 700.0 (35 @ eff)
                u6 : 0(38 @ f04)
                u7 : 0.0 (45 @ f06)
			}
		}

        component sub-sub-block { (1a @ f0b)

            component type : CollectableItem (0a @ f0d)
            number : 2(10 @ f1e)

            collectable item sub-sub-sub-block { (fb2 @ f21)

                u0 : 0(08 @ f23)
                u1 : 0(10 @ f25)

                lua chunk sub-sub-sub-sub-block { (1a @ f27)

				}
                name :  (22 @ f29)
                ?model : icetrinket (2a @ f2b)
                u0 : 1(30 @ f37)
			}
		}

        component sub-sub-block { (1a @ f39)

            component type : ModelTransformController (0a @ f3b)
            number : 3(10 @ f55)

            model transform controller sub-sub-sub-block { (342 @ f58)

                u0 : 101(08 @ f5a)
                u2 : 3.1415927410125732 (2d @ f5c)
			}
		}

        component sub-sub-block { (1a @ f61)

            component type : Model (0a @ f63)
            number : 101(10 @ f6a)

            3D model sub-sub-sub-block { (32a @ f6d)

                name : item_icetrinket (0a @ f6f)
                u0 : 0.0 (15 @ f80)
                u1 : 5.0 (1d @ f85)
                u2 : 0.0 (25 @ f8a)

                u3 sub-sub-sub-sub-block { (2a @ f8f)

                    w : 0.0 (0d @ f91)
                    x : 0.0 (15 @ f96)
                    y : 0.0 (1d @ f9b)
                    z : 1.0 (25 @ fa0)
				}

                u4 sub-sub-sub-sub-block { (32 @ fa5)

                    x : 0.0 (0d @ fa7)
                    y : -15.0 (15 @ fac)
                    z : 0.0 (1d @ fb1)
				}
                u5 : 0(38 @ fb6)

                u6 sub-sub-sub-sub-block { (42 @ fb8)

                    w : 1.0 (0d @ fba)
                    x : 1.0 (15 @ fbf)
                    y : 1.0 (1d @ fc4)
                    z : 1.0 (25 @ fc9)
				}
			}
		}

        component sub-sub-block { (1a @ fce)

            component type : SimpleGlow (0a @ fd0)
            number : 102(10 @ fdc)

            simple glow sub-sub-sub-block { (7f2 @ fdf)


                u0 sub-sub-sub-sub-block { (0a @ fe1)

                    w : 0.3222222328186035 (0d @ fe3)
                    x : 0.46666666865348816 (15 @ fe8)
                    y : 1.0 (1d @ fed)
                    z : 0.6333333253860474 (25 @ ff2)
				}
                u1 : 25.0 (15 @ ff7)
                u2 : 16(18 @ ffc)
                u3 : 15.0 (25 @ ffe)
                u4 : 0.15000000596046448 (2d @ 1003)
                u5 : 1.2000000476837158 (35 @ 1008)

                u6 sub-sub-sub-sub-block { (3a @ 100d)

                    y : 0.0 (0d @ 100f)
                    z : 15.0 (15 @ 1014)
				}
			}
		}

        component sub-sub-block { (1a @ 1019)

            component type : CollisionShape (0a @ 101b)
            number : 105(10 @ 102b)

            collision shape sub-sub-sub-block { (3c2 @ 102e)


                u0 sub-sub-sub-sub-block { (0a @ 1030)

                    w : -5.0 (0d @ 1032)
                    x : 0.0 (15 @ 1037)
                    y : 10.0 (1d @ 103c)
                    z : 30.0 (25 @ 1041)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1047)

                u1 : 1(18 @ 1049)
                w : -40.0 (35 @ 104b)
                x : 40.0 (3d @ 1050)
                y : 3(40 @ 1055)
                z : 1(58 @ 1057)
			}
		}

        position sub-sub-block { (22 @ 1059)

            x position : 0.0 (0d @ 105b)
            y position : 0.0 (15 @ 1060)
		}
        z position : 0.0 (2d @ 1065)
        rotation : 0.0 (35 @ 106a)
        scale : 1.0 (3d @ 106f)

        u0 sub-sub-block { (42 @ 1074)

            w : -25.0 (0d @ 1076)
            x : -25.0 (15 @ 107b)
            y : 50.0 (1d @ 1080)
            z : 55.0 (25 @ 1085)
		}
        hidden : 0(48 @ 108a)
	}
    u0 : 1.0 (15 @ 108c)
}

?item block { (12 @ 1091)


    ?sub-item sub-block { (0a @ 1094)

        name : item_ironsword (12 @ 1097)

        component sub-sub-block { (1a @ 10a7)

            component type : PhysicsObject (0a @ 10a9)
            number : 1(10 @ 10b8)

            physics object sub-sub-sub-block { (4fa @ 10bb)

                u0 : 1(08 @ 10bd)
                u2 : 0.5 (1d @ 10bf)
                u3 : 1500.0 (25 @ 10c4)
                u4 : 0.0 (2d @ 10c9)
                u5 : 700.0 (35 @ 10ce)
                u6 : 0(38 @ 10d3)
                u7 : 0.0 (45 @ 10d5)
			}
		}

        component sub-sub-block { (1a @ 10da)

            component type : CollectableItem (0a @ 10dc)
            number : 2(10 @ 10ed)

            collectable item sub-sub-sub-block { (fb2 @ 10f0)

                u0 : 0(08 @ 10f2)
                u1 : 0(10 @ 10f4)

                lua chunk sub-sub-sub-sub-block { (1a @ 10f6)

				}
                name :  (22 @ 10f8)
                ?model : ironsword (2a @ 10fa)
                u0 : 1(30 @ 1105)
			}
		}

        component sub-sub-block { (1a @ 1107)

            component type : ModelTransformController (0a @ 1109)
            number : 3(10 @ 1123)

            model transform controller sub-sub-sub-block { (342 @ 1126)

                u0 : 101(08 @ 1128)
                u2 : 3.1415927410125732 (2d @ 112a)
			}
		}

        component sub-sub-block { (1a @ 112f)

            component type : Model (0a @ 1131)
            number : 101(10 @ 1138)

            3D model sub-sub-sub-block { (32a @ 113b)

                name : weapon_ironsword (0a @ 113d)
                u0 : 0.7853981852531433 (15 @ 114f)
                u1 : 1.0 (1d @ 1154)
                u2 : 1.5707963705062866 (25 @ 1159)

                u3 sub-sub-sub-sub-block { (2a @ 115e)

                    w : 0.0 (0d @ 1160)
                    x : 0.0 (15 @ 1165)
                    y : 0.0 (1d @ 116a)
                    z : 1.0 (25 @ 116f)
				}

                u4 sub-sub-sub-sub-block { (32 @ 1174)

                    x : 15.0 (0d @ 1176)
                    y : 0.0 (15 @ 117b)
                    z : 0.0 (1d @ 1180)
				}
                u5 : 0(38 @ 1185)

                u6 sub-sub-sub-sub-block { (42 @ 1187)

                    w : 1.0 (0d @ 1189)
                    x : 1.0 (15 @ 118e)
                    y : 1.0 (1d @ 1193)
                    z : 1.0 (25 @ 1198)
				}
			}
		}

        component sub-sub-block { (1a @ 119d)

            component type : SimpleGlow (0a @ 119f)
            number : 102(10 @ 11ab)

            simple glow sub-sub-sub-block { (7f2 @ 11ae)


                u0 sub-sub-sub-sub-block { (0a @ 11b0)

                    w : 0.12263374030590057 (0d @ 11b2)
                    x : 0.18696410953998566 (15 @ 11b7)
                    y : 0.23292176425457 (1d @ 11bc)
                    z : 0.0 (25 @ 11c1)
				}
                u1 : 25.0 (15 @ 11c6)
                u2 : 15(18 @ 11cb)
                u3 : 15.0 (25 @ 11cd)
                u4 : 0.15000000596046448 (2d @ 11d2)
                u5 : 0.800000011920929 (35 @ 11d7)

                u6 sub-sub-sub-sub-block { (3a @ 11dc)

                    y : 0.0 (0d @ 11de)
                    z : 15.0 (15 @ 11e3)
				}
			}
		}

        component sub-sub-block { (1a @ 11e8)

            component type : CollisionShape (0a @ 11ea)
            number : 105(10 @ 11fa)

            collision shape sub-sub-sub-block { (3c2 @ 11fd)


                u0 sub-sub-sub-sub-block { (0a @ 11ff)

                    w : -15.0 (0d @ 1201)
                    x : -8.0 (15 @ 1206)
                    y : 30.0 (1d @ 120b)
                    z : 38.0 (25 @ 1210)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1216)

                u1 : 1(18 @ 1218)
                w : -40.0 (35 @ 121a)
                x : 40.0 (3d @ 121f)
                y : 3(40 @ 1224)
                z : 1(58 @ 1226)
			}
		}

        position sub-sub-block { (22 @ 1228)

            x position : 0.0 (0d @ 122a)
            y position : 0.0 (15 @ 122f)
		}
        z position : 0.0 (2d @ 1234)
        rotation : 0.0 (35 @ 1239)
        scale : 1.0 (3d @ 123e)

        u0 sub-sub-block { (42 @ 1243)

            w : -25.0 (0d @ 1245)
            x : -25.0 (15 @ 124a)
            y : 50.0 (1d @ 124f)
            z : 55.0 (25 @ 1254)
		}
        hidden : 0(48 @ 1259)
	}
    u0 : 0.800000011920929 (15 @ 125b)
}

?item block { (12 @ 1260)


    ?sub-item sub-block { (0a @ 1263)

        name : item_key_yellow (12 @ 1266)

        component sub-sub-block { (1a @ 1277)

            component type : PhysicsObject (0a @ 1279)
            number : 1(10 @ 1288)

            physics object sub-sub-sub-block { (4fa @ 128b)

                u0 : 1(08 @ 128d)
                u3 : 1500.0 (25 @ 128f)
                u4 : 0.0 (2d @ 1294)
                u5 : 700.0 (35 @ 1299)
                u6 : 0(38 @ 129e)
                u7 : 0.0 (45 @ 12a0)
			}
		}

        component sub-sub-block { (1a @ 12a5)

            component type : CollectableItem (0a @ 12a8)
            number : 2(10 @ 12b9)

            collectable item sub-sub-sub-block { (fb2 @ 12bc)

                u0 : 0(08 @ 12bf)
                u1 : 0(10 @ 12c1)

                lua chunk sub-sub-sub-sub-block { (1a @ 12c3)

                    main chunk : chunk >

                    === lua =============
                    local self = ...;
                    
                    SoundLibrary.PlayEffect("surprise2");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00;\x00\x00\x00local self = ...;\r\n\r\nSoundLibrary.PlayEffect("surprise2");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\x06\x00\x00\x00%\x00\x00\x01E\x00\x00\x00F@\xc0\x00\x81\x80\x00\x00\\@\x00\x01\x1e\x00\x80\x00\x03\x00\x00\x00\x04\r\x00\x00\x00SoundLibrary\x00\x04\x0b\x00\x00\x00PlayEffect\x00\x04\n\x00\x00\x00surprise2\x00\x00\x00\x00\x00\x06\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00self\x00\x01\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00 (12 @ 1302)
				}
                name :  (22 @ 13e6)
                ?model : key_yellow (2a @ 13e8)
                u0 : 0(30 @ 13f4)
			}
		}

        component sub-sub-block { (1a @ 13f6)

            component type : ModelTransformController (0a @ 13f8)
            number : 3(10 @ 1412)

            model transform controller sub-sub-sub-block { (342 @ 1415)

                u0 : 101(08 @ 1417)
                u2 : 3.3161256313323975 (2d @ 1419)
			}
		}

        component sub-sub-block { (1a @ 141e)

            component type : Model (0a @ 1420)
            number : 101(10 @ 1427)

            3D model sub-sub-sub-block { (32a @ 142a)

                name : item_key_yellow (0a @ 142c)
                u0 : 0.0 (15 @ 143d)
                u1 : 5.0 (1d @ 1442)
                u2 : 0.0 (25 @ 1447)

                u3 sub-sub-sub-sub-block { (2a @ 144c)

                    w : 0.0 (0d @ 144e)
                    x : 0.0 (15 @ 1453)
                    y : 0.0 (1d @ 1458)
                    z : 1.0 (25 @ 145d)
				}

                u4 sub-sub-sub-sub-block { (32 @ 1462)

                    x : 0.0 (0d @ 1464)
                    y : -15.0 (15 @ 1469)
                    z : 0.0 (1d @ 146e)
				}
                u5 : 0(38 @ 1473)

                u6 sub-sub-sub-sub-block { (42 @ 1475)

                    w : 1.0 (0d @ 1477)
                    x : 1.0 (15 @ 147c)
                    y : 1.0 (1d @ 1481)
                    z : 1.0 (25 @ 1486)
				}
			}
		}

        component sub-sub-block { (1a @ 148b)

            component type : SimpleGlow (0a @ 148d)
            number : 102(10 @ 1499)

            simple glow sub-sub-sub-block { (7f2 @ 149c)


                u0 sub-sub-sub-sub-block { (0a @ 149e)

                    w : 0.8000001907348633 (0d @ 14a0)
                    x : 0.8000000715255737 (15 @ 14a5)
                    y : 0.0 (1d @ 14aa)
                    z : 0.5 (25 @ 14af)
				}
                u1 : 15.0 (15 @ 14b4)
                u2 : 8(18 @ 14b9)
                u3 : 15.0 (25 @ 14bb)
                u4 : 0.15000000596046448 (2d @ 14c0)
                u5 : 0.800000011920929 (35 @ 14c5)

                u6 sub-sub-sub-sub-block { (3a @ 14ca)

                    y : 0.0 (0d @ 14cc)
                    z : 15.0 (15 @ 14d1)
				}
			}
		}

        component sub-sub-block { (1a @ 14d6)

            component type : CollisionShape (0a @ 14d8)
            number : 105(10 @ 14e8)

            collision shape sub-sub-sub-block { (3c2 @ 14eb)


                u0 sub-sub-sub-sub-block { (0a @ 14ed)

                    w : -5.0 (0d @ 14ef)
                    x : 0.0 (15 @ 14f4)
                    y : 10.0 (1d @ 14f9)
                    z : 30.0 (25 @ 14fe)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1504)

                u1 : 1(18 @ 1506)
                w : -40.0 (35 @ 1508)
                x : 40.0 (3d @ 150d)
                y : 3(40 @ 1512)
                z : 1(58 @ 1514)
			}
		}

        position sub-sub-block { (22 @ 1516)

            x position : 0.0 (0d @ 1518)
            y position : 0.0 (15 @ 151d)
		}
        z position : 0.0 (2d @ 1522)
        rotation : 0.0 (35 @ 1527)
        scale : 1.0 (3d @ 152c)

        u0 sub-sub-block { (42 @ 1531)

            w : -15.0 (0d @ 1533)
            x : -15.0 (15 @ 1538)
            y : 30.0 (1d @ 153d)
            z : 45.0 (25 @ 1542)
		}
        hidden : 0(48 @ 1547)
	}
    u0 : 1.0 (15 @ 1549)
}

?item block { (12 @ 154e)


    ?sub-item sub-block { (0a @ 1551)

        name : item_key_yellow_shop (12 @ 1554)

        component sub-sub-block { (1a @ 156a)

            component type : PhysicsObject (0a @ 156c)
            number : 1(10 @ 157b)

            physics object sub-sub-sub-block { (4fa @ 157e)

                u0 : 1(08 @ 1580)
                u3 : 1500.0 (25 @ 1582)
                u4 : 0.0 (2d @ 1587)
                u5 : 700.0 (35 @ 158c)
                u6 : 0(38 @ 1591)
                u7 : 0.0 (45 @ 1593)
			}
		}

        component sub-sub-block { (1a @ 1598)

            component type : CollectableItem (0a @ 159b)
            number : 2(10 @ 15ac)

            collectable item sub-sub-sub-block { (fb2 @ 15af)

                u0 : 0(08 @ 15b2)
                u1 : 0(10 @ 15b4)

                lua chunk sub-sub-sub-sub-block { (1a @ 15b6)

                    main chunk : chunk >

                    === lua =============
                    local self = ...;
                    
                    SoundLibrary.PlayEffect("surprise2");
                    Game.IncCounter("takingtheshortcut");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00b\x00\x00\x00local self = ...;\r\n\r\nSoundLibrary.PlayEffect("surprise2");\r\nGame.IncCounter("takingtheshortcut");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\n\x00\x00\x00%\x00\x00\x01E\x00\x00\x00F@\xc0\x00\x81\x80\x00\x00\\@\x00\x01E\xc0\x00\x00F\x00\xc1\x00\x81@\x01\x00\\@\x00\x01\x1e\x00\x80\x00\x06\x00\x00\x00\x04\r\x00\x00\x00SoundLibrary\x00\x04\x0b\x00\x00\x00PlayEffect\x00\x04\n\x00\x00\x00surprise2\x00\x04\x05\x00\x00\x00Game\x00\x04\x0b\x00\x00\x00IncCounter\x00\x04\x12\x00\x00\x00takingtheshortcut\x00\x00\x00\x00\x00\n\x00\x00\x00\x01\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00self\x00\x01\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00 (12 @ 161c)
				}
                name :  (22 @ 1778)
                ?model : key_yellow (2a @ 177a)
                u0 : 0(30 @ 1786)
			}
		}

        component sub-sub-block { (1a @ 1788)

            component type : ModelTransformController (0a @ 178a)
            number : 3(10 @ 17a4)

            model transform controller sub-sub-sub-block { (342 @ 17a7)

                u0 : 101(08 @ 17a9)
                u2 : 3.3161256313323975 (2d @ 17ab)
			}
		}

        component sub-sub-block { (1a @ 17b0)

            component type : Model (0a @ 17b2)
            number : 101(10 @ 17b9)

            3D model sub-sub-sub-block { (32a @ 17bc)

                name : item_key_yellow (0a @ 17be)
                u0 : 0.0 (15 @ 17cf)
                u1 : 5.0 (1d @ 17d4)
                u2 : 0.0 (25 @ 17d9)

                u3 sub-sub-sub-sub-block { (2a @ 17de)

                    w : 0.0 (0d @ 17e0)
                    x : 0.0 (15 @ 17e5)
                    y : 0.0 (1d @ 17ea)
                    z : 1.0 (25 @ 17ef)
				}

                u4 sub-sub-sub-sub-block { (32 @ 17f4)

                    x : 0.0 (0d @ 17f6)
                    y : -15.0 (15 @ 17fb)
                    z : 0.0 (1d @ 1800)
				}
                u5 : 0(38 @ 1805)

                u6 sub-sub-sub-sub-block { (42 @ 1807)

                    w : 1.0 (0d @ 1809)
                    x : 1.0 (15 @ 180e)
                    y : 1.0 (1d @ 1813)
                    z : 1.0 (25 @ 1818)
				}
			}
		}

        component sub-sub-block { (1a @ 181d)

            component type : SimpleGlow (0a @ 181f)
            number : 102(10 @ 182b)

            simple glow sub-sub-sub-block { (7f2 @ 182e)


                u0 sub-sub-sub-sub-block { (0a @ 1830)

                    w : 0.8000001907348633 (0d @ 1832)
                    x : 0.8000000715255737 (15 @ 1837)
                    y : 0.0 (1d @ 183c)
                    z : 0.5 (25 @ 1841)
				}
                u1 : 15.0 (15 @ 1846)
                u2 : 8(18 @ 184b)
                u3 : 15.0 (25 @ 184d)
                u4 : 0.15000000596046448 (2d @ 1852)
                u5 : 0.800000011920929 (35 @ 1857)

                u6 sub-sub-sub-sub-block { (3a @ 185c)

                    y : 0.0 (0d @ 185e)
                    z : 15.0 (15 @ 1863)
				}
			}
		}

        component sub-sub-block { (1a @ 1868)

            component type : CollisionShape (0a @ 186a)
            number : 105(10 @ 187a)

            collision shape sub-sub-sub-block { (3c2 @ 187d)


                u0 sub-sub-sub-sub-block { (0a @ 187f)

                    w : -5.0 (0d @ 1881)
                    x : 0.0 (15 @ 1886)
                    y : 10.0 (1d @ 188b)
                    z : 30.0 (25 @ 1890)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1896)

                u1 : 1(18 @ 1898)
                w : -40.0 (35 @ 189a)
                x : 40.0 (3d @ 189f)
                y : 3(40 @ 18a4)
                z : 1(58 @ 18a6)
			}
		}

        position sub-sub-block { (22 @ 18a8)

            x position : 0.0 (0d @ 18aa)
            y position : 0.0 (15 @ 18af)
		}
        z position : 0.0 (2d @ 18b4)
        rotation : 0.0 (35 @ 18b9)
        scale : 1.0 (3d @ 18be)

        u0 sub-sub-block { (42 @ 18c3)

            w : -15.0 (0d @ 18c5)
            x : -15.0 (15 @ 18ca)
            y : 30.0 (1d @ 18cf)
            z : 45.0 (25 @ 18d4)
		}
        hidden : 0(48 @ 18d9)
	}
    u0 : 1.0 (15 @ 18db)
}

?item block { (12 @ 18e0)


    ?sub-item sub-block { (0a @ 18e3)

        name : item_legendsword (12 @ 18e6)

        component sub-sub-block { (1a @ 18f8)

            component type : PhysicsObject (0a @ 18fa)
            number : 1(10 @ 1909)

            physics object sub-sub-sub-block { (4fa @ 190c)

                u0 : 1(08 @ 190e)
                u2 : 0.5 (1d @ 1910)
                u3 : 1500.0 (25 @ 1915)
                u4 : 0.0 (2d @ 191a)
                u5 : 700.0 (35 @ 191f)
                u6 : 0(38 @ 1924)
                u7 : 0.0 (45 @ 1926)
			}
		}

        component sub-sub-block { (1a @ 192b)

            component type : CollectableItem (0a @ 192d)
            number : 2(10 @ 193e)

            collectable item sub-sub-sub-block { (fb2 @ 1941)

                u0 : 0(08 @ 1943)
                u1 : 0(10 @ 1945)

                lua chunk sub-sub-sub-sub-block { (1a @ 1947)

				}
                name :  (22 @ 1949)
                ?model : legendsword (2a @ 194b)
                u0 : 1(30 @ 1958)
			}
		}

        component sub-sub-block { (1a @ 195a)

            component type : ModelTransformController (0a @ 195c)
            number : 3(10 @ 1976)

            model transform controller sub-sub-sub-block { (342 @ 1979)

                u0 : 101(08 @ 197b)
                u2 : 3.1415927410125732 (2d @ 197d)
			}
		}

        component sub-sub-block { (1a @ 1982)

            component type : Model (0a @ 1984)
            number : 101(10 @ 198b)

            3D model sub-sub-sub-block { (32a @ 198e)

                name : weapon_legendsword (0a @ 1990)
                u0 : 0.7853981852531433 (15 @ 19a4)
                u1 : 1.0 (1d @ 19a9)
                u2 : 1.5707963705062866 (25 @ 19ae)

                u3 sub-sub-sub-sub-block { (2a @ 19b3)

                    w : 0.0 (0d @ 19b5)
                    x : 0.0 (15 @ 19ba)
                    y : 0.0 (1d @ 19bf)
                    z : 1.0 (25 @ 19c4)
				}

                u4 sub-sub-sub-sub-block { (32 @ 19c9)

                    x : 15.0 (0d @ 19cb)
                    y : -5.0 (15 @ 19d0)
                    z : 0.0 (1d @ 19d5)
				}
                u5 : 0(38 @ 19da)

                u6 sub-sub-sub-sub-block { (42 @ 19dc)

                    w : 1.0 (0d @ 19de)
                    x : 1.0 (15 @ 19e3)
                    y : 1.0 (1d @ 19e8)
                    z : 1.0 (25 @ 19ed)
				}
			}
		}

        component sub-sub-block { (1a @ 19f2)

            component type : SimpleGlow (0a @ 19f4)
            number : 102(10 @ 1a00)

            simple glow sub-sub-sub-block { (7f2 @ 1a03)


                u0 sub-sub-sub-sub-block { (0a @ 1a05)

                    w : 0.3283950686454773 (0d @ 1a07)
                    x : 0.45822399854660034 (15 @ 1a0c)
                    y : 0.5160493850708008 (1d @ 1a11)
                    z : 0.0 (25 @ 1a16)
				}
                u1 : 40.0 (15 @ 1a1b)
                u2 : 15(18 @ 1a20)
                u3 : 15.0 (25 @ 1a22)
                u4 : 0.15000000596046448 (2d @ 1a27)
                u5 : 0.800000011920929 (35 @ 1a2c)

                u6 sub-sub-sub-sub-block { (3a @ 1a31)

                    y : 0.0 (0d @ 1a33)
                    z : 15.0 (15 @ 1a38)
				}
			}
		}

        component sub-sub-block { (1a @ 1a3d)

            component type : CollisionShape (0a @ 1a3f)
            number : 105(10 @ 1a4f)

            collision shape sub-sub-sub-block { (3c2 @ 1a52)


                u0 sub-sub-sub-sub-block { (0a @ 1a54)

                    w : -15.0 (0d @ 1a56)
                    x : -15.0 (15 @ 1a5b)
                    y : 30.0 (1d @ 1a60)
                    z : 45.0 (25 @ 1a65)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1a6b)

                u1 : 1(18 @ 1a6d)
                w : -40.0 (35 @ 1a6f)
                x : 40.0 (3d @ 1a74)
                y : 3(40 @ 1a79)
                z : 1(58 @ 1a7b)
			}
		}

        position sub-sub-block { (22 @ 1a7d)

            x position : 0.0 (0d @ 1a7f)
            y position : 0.0 (15 @ 1a84)
		}
        z position : 0.0 (2d @ 1a89)
        rotation : 0.0 (35 @ 1a8e)
        scale : 1.0 (3d @ 1a93)

        u0 sub-sub-block { (42 @ 1a98)

            w : -40.0 (0d @ 1a9a)
            x : -40.0 (15 @ 1a9f)
            y : 80.0 (1d @ 1aa4)
            z : 80.0 (25 @ 1aa9)
		}
        hidden : 0(48 @ 1aae)
	}
    u0 : 0.800000011920929 (15 @ 1ab0)
}

?item block { (12 @ 1ab5)


    ?sub-item sub-block { (0a @ 1ab8)

        name : item_magicarmor (12 @ 1abb)

        component sub-sub-block { (1a @ 1acc)

            component type : PhysicsObject (0a @ 1ace)
            number : 1(10 @ 1add)

            physics object sub-sub-sub-block { (4fa @ 1ae0)

                u0 : 1(08 @ 1ae2)
                u2 : 0.5 (1d @ 1ae4)
                u3 : 1500.0 (25 @ 1ae9)
                u4 : 0.0 (2d @ 1aee)
                u5 : 700.0 (35 @ 1af3)
                u6 : 0(38 @ 1af8)
                u7 : 0.0 (45 @ 1afa)
			}
		}

        component sub-sub-block { (1a @ 1aff)

            component type : CollectableItem (0a @ 1b01)
            number : 2(10 @ 1b12)

            collectable item sub-sub-sub-block { (fb2 @ 1b15)

                u0 : 0(08 @ 1b17)
                u1 : 0(10 @ 1b19)

                lua chunk sub-sub-sub-sub-block { (1a @ 1b1b)

				}
                name :  (22 @ 1b1d)
                ?model : magicarmor (2a @ 1b1f)
                u0 : 1(30 @ 1b2b)
			}
		}

        component sub-sub-block { (1a @ 1b2d)

            component type : ModelTransformController (0a @ 1b2f)
            number : 3(10 @ 1b49)

            model transform controller sub-sub-sub-block { (342 @ 1b4c)

                u0 : 101(08 @ 1b4e)
                u2 : 3.1415927410125732 (2d @ 1b50)
			}
		}

        component sub-sub-block { (1a @ 1b55)

            component type : Model (0a @ 1b57)
            number : 101(10 @ 1b5e)

            3D model sub-sub-sub-block { (32a @ 1b61)

                name : item_magicplate (0a @ 1b63)
                u0 : 0.0 (15 @ 1b74)
                u1 : 1.0 (1d @ 1b79)
                u2 : 0.0 (25 @ 1b7e)

                u3 sub-sub-sub-sub-block { (2a @ 1b83)

                    w : 0.0 (0d @ 1b85)
                    x : 0.0 (15 @ 1b8a)
                    y : 0.0 (1d @ 1b8f)
                    z : 1.0 (25 @ 1b94)
				}

                u4 sub-sub-sub-sub-block { (32 @ 1b99)

                    x : 0.0 (0d @ 1b9b)
                    y : -16.0 (15 @ 1ba0)
                    z : 0.0 (1d @ 1ba5)
				}
                u5 : 0(38 @ 1baa)

                u6 sub-sub-sub-sub-block { (42 @ 1bac)

                    w : 1.0 (0d @ 1bae)
                    x : 1.0 (15 @ 1bb3)
                    y : 1.0 (1d @ 1bb8)
                    z : 1.0 (25 @ 1bbd)
				}
			}
		}

        component sub-sub-block { (1a @ 1bc2)

            component type : SimpleGlow (0a @ 1bc4)
            number : 102(10 @ 1bd0)

            simple glow sub-sub-sub-block { (7f2 @ 1bd3)


                u0 sub-sub-sub-sub-block { (0a @ 1bd5)

                    w : 0.37457817792892456 (0d @ 1bd7)
                    x : 0.1365329623222351 (15 @ 1bdc)
                    y : 0.20001177489757538 (1d @ 1be1)
                    z : 0.3333333432674408 (25 @ 1be6)
				}
                u1 : 20.0 (15 @ 1beb)
                u2 : 15(18 @ 1bf0)
                u3 : 25.0 (25 @ 1bf2)
                u4 : 0.15000000596046448 (2d @ 1bf7)
                u5 : 0.800000011920929 (35 @ 1bfc)

                u6 sub-sub-sub-sub-block { (3a @ 1c01)

                    y : 0.0 (0d @ 1c03)
                    z : 15.0 (15 @ 1c08)
				}
			}
		}

        component sub-sub-block { (1a @ 1c0d)

            component type : CollisionShape (0a @ 1c0f)
            number : 105(10 @ 1c1f)

            collision shape sub-sub-sub-block { (3c2 @ 1c22)


                u0 sub-sub-sub-sub-block { (0a @ 1c24)

                    w : -15.0 (0d @ 1c26)
                    x : -8.0 (15 @ 1c2b)
                    y : 30.0 (1d @ 1c30)
                    z : 38.0 (25 @ 1c35)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1c3b)

                u1 : 1(18 @ 1c3d)
                w : -40.0 (35 @ 1c3f)
                x : 40.0 (3d @ 1c44)
                y : 3(40 @ 1c49)
                z : 1(58 @ 1c4b)
			}
		}

        position sub-sub-block { (22 @ 1c4d)

            x position : 0.0 (0d @ 1c4f)
            y position : 0.0 (15 @ 1c54)
		}
        z position : 0.0 (2d @ 1c59)
        rotation : 0.0 (35 @ 1c5e)
        scale : 1.0 (3d @ 1c63)

        u0 sub-sub-block { (42 @ 1c68)

            w : -20.0 (0d @ 1c6a)
            x : -20.0 (15 @ 1c6f)
            y : 40.0 (1d @ 1c74)
            z : 50.0 (25 @ 1c79)
		}
        hidden : 0(48 @ 1c7e)
	}
    u0 : 1.5 (15 @ 1c80)
}

?item block { (12 @ 1c85)


    ?sub-item sub-block { (0a @ 1c88)

        name : item_magicsword (12 @ 1c8b)

        component sub-sub-block { (1a @ 1c9c)

            component type : PhysicsObject (0a @ 1c9e)
            number : 1(10 @ 1cad)

            physics object sub-sub-sub-block { (4fa @ 1cb0)

                u0 : 1(08 @ 1cb2)
                u2 : 0.5 (1d @ 1cb4)
                u3 : 1500.0 (25 @ 1cb9)
                u4 : 0.0 (2d @ 1cbe)
                u5 : 700.0 (35 @ 1cc3)
                u6 : 0(38 @ 1cc8)
                u7 : 0.0 (45 @ 1cca)
			}
		}

        component sub-sub-block { (1a @ 1ccf)

            component type : CollectableItem (0a @ 1cd2)
            number : 2(10 @ 1ce3)

            collectable item sub-sub-sub-block { (fb2 @ 1ce6)

                u0 : 0(08 @ 1ce9)
                u1 : 0(10 @ 1ceb)

                lua chunk sub-sub-sub-sub-block { (1a @ 1ced)

                    main chunk : chunk >

                    === lua =============
                    Game.IncCounter("lordoftheundead");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00$\x00\x00\x00Game.IncCounter("lordoftheundead");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x05\x00\x00\x00\x05\x00\x00\x00\x06@@\x00A\x80\x00\x00\x1c@\x00\x01\x1e\x00\x80\x00\x03\x00\x00\x00\x04\x05\x00\x00\x00Game\x00\x04\x0b\x00\x00\x00IncCounter\x00\x04\x10\x00\x00\x00lordoftheundead\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 (12 @ 1d15)
				}
                name :  (22 @ 1dc7)
                ?model : magicsword (2a @ 1dc9)
                u0 : 1(30 @ 1dd5)
			}
		}

        component sub-sub-block { (1a @ 1dd7)

            component type : ModelTransformController (0a @ 1dd9)
            number : 3(10 @ 1df3)

            model transform controller sub-sub-sub-block { (342 @ 1df6)

                u0 : 101(08 @ 1df8)
                u2 : 3.1415927410125732 (2d @ 1dfa)
			}
		}

        component sub-sub-block { (1a @ 1dff)

            component type : Model (0a @ 1e01)
            number : 101(10 @ 1e08)

            3D model sub-sub-sub-block { (32a @ 1e0b)

                name : weapon_magicsword (0a @ 1e0d)
                u0 : 0.7853981852531433 (15 @ 1e20)
                u1 : 1.0 (1d @ 1e25)
                u2 : 1.5707963705062866 (25 @ 1e2a)

                u3 sub-sub-sub-sub-block { (2a @ 1e2f)

                    w : 0.0 (0d @ 1e31)
                    x : 0.0 (15 @ 1e36)
                    y : 0.0 (1d @ 1e3b)
                    z : 1.0 (25 @ 1e40)
				}

                u4 sub-sub-sub-sub-block { (32 @ 1e45)

                    x : 15.0 (0d @ 1e47)
                    y : 0.0 (15 @ 1e4c)
                    z : 0.0 (1d @ 1e51)
				}
                u5 : 0(38 @ 1e56)

                u6 sub-sub-sub-sub-block { (42 @ 1e58)

                    w : 1.0 (0d @ 1e5a)
                    x : 1.0 (15 @ 1e5f)
                    y : 1.0 (1d @ 1e64)
                    z : 1.0 (25 @ 1e69)
				}
			}
		}

        component sub-sub-block { (1a @ 1e6e)

            component type : SimpleGlow (0a @ 1e70)
            number : 102(10 @ 1e7c)

            simple glow sub-sub-sub-block { (7f2 @ 1e7f)


                u0 sub-sub-sub-sub-block { (0a @ 1e81)

                    w : 0.3283950686454773 (0d @ 1e83)
                    x : 0.45822399854660034 (15 @ 1e88)
                    y : 0.5160493850708008 (1d @ 1e8d)
                    z : 0.0 (25 @ 1e92)
				}
                u1 : 40.0 (15 @ 1e97)
                u2 : 15(18 @ 1e9c)
                u3 : 15.0 (25 @ 1e9e)
                u4 : 0.15000000596046448 (2d @ 1ea3)
                u5 : 0.800000011920929 (35 @ 1ea8)

                u6 sub-sub-sub-sub-block { (3a @ 1ead)

                    y : 0.0 (0d @ 1eaf)
                    z : 15.0 (15 @ 1eb4)
				}
			}
		}

        component sub-sub-block { (1a @ 1eb9)

            component type : CollisionShape (0a @ 1ebb)
            number : 105(10 @ 1ecb)

            collision shape sub-sub-sub-block { (3c2 @ 1ece)


                u0 sub-sub-sub-sub-block { (0a @ 1ed0)

                    w : -15.0 (0d @ 1ed2)
                    x : -15.0 (15 @ 1ed7)
                    y : 30.0 (1d @ 1edc)
                    z : 45.0 (25 @ 1ee1)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 1ee7)

                u1 : 1(18 @ 1ee9)
                w : -40.0 (35 @ 1eeb)
                x : 40.0 (3d @ 1ef0)
                y : 3(40 @ 1ef5)
                z : 1(58 @ 1ef7)
			}
		}

        position sub-sub-block { (22 @ 1ef9)

            x position : 0.0 (0d @ 1efb)
            y position : 0.0 (15 @ 1f00)
		}
        z position : 0.0 (2d @ 1f05)
        rotation : 0.0 (35 @ 1f0a)
        scale : 1.0 (3d @ 1f0f)

        u0 sub-sub-block { (42 @ 1f14)

            w : -40.0 (0d @ 1f16)
            x : -40.0 (15 @ 1f1b)
            y : 80.0 (1d @ 1f20)
            z : 80.0 (25 @ 1f25)
		}
        hidden : 0(48 @ 1f2a)
	}
    u0 : 1.0 (15 @ 1f2c)
}

?item block { (12 @ 1f31)


    ?sub-item sub-block { (0a @ 1f34)

        name : item_needle (12 @ 1f37)

        component sub-sub-block { (1a @ 1f44)

            component type : PhysicsObject (0a @ 1f46)
            number : 1(10 @ 1f55)

            physics object sub-sub-sub-block { (4fa @ 1f58)

                u0 : 1(08 @ 1f5a)
                u2 : 0.5 (1d @ 1f5c)
                u3 : 1500.0 (25 @ 1f61)
                u4 : 0.0 (2d @ 1f66)
                u5 : 700.0 (35 @ 1f6b)
                u6 : 0(38 @ 1f70)
                u7 : 0.0 (45 @ 1f72)
			}
		}

        component sub-sub-block { (1a @ 1f77)

            component type : CollectableItem (0a @ 1f7a)
            number : 2(10 @ 1f8b)

            collectable item sub-sub-sub-block { (fb2 @ 1f8e)

                u0 : 0(08 @ 1f91)
                u1 : 0(10 @ 1f93)

                lua chunk sub-sub-sub-sub-block { (1a @ 1f95)

                    main chunk : chunk >

                    === lua =============
                    Game.IncCounter("lostsword");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00\x1e\x00\x00\x00Game.IncCounter("lostsword");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x05\x00\x00\x00\x05\x00\x00\x00\x06@@\x00A\x80\x00\x00\x1c@\x00\x01\x1e\x00\x80\x00\x03\x00\x00\x00\x04\x05\x00\x00\x00Game\x00\x04\x0b\x00\x00\x00IncCounter\x00\x04\n\x00\x00\x00lostsword\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 (12 @ 1fb7)
				}
                name :  (22 @ 205d)
                ?model : needle (2a @ 205f)
                u0 : 1(30 @ 2067)
			}
		}

        component sub-sub-block { (1a @ 2069)

            component type : ModelTransformController (0a @ 206b)
            number : 3(10 @ 2085)

            model transform controller sub-sub-sub-block { (342 @ 2088)

                u0 : 101(08 @ 208a)
                u2 : 3.1415927410125732 (2d @ 208c)
			}
		}

        component sub-sub-block { (1a @ 2091)

            component type : Model (0a @ 2093)
            number : 101(10 @ 209a)

            3D model sub-sub-sub-block { (32a @ 209d)

                name : weapon_ironsword (0a @ 209f)
                u0 : 0.7853981852531433 (15 @ 20b1)
                u1 : 1.0 (1d @ 20b6)
                u2 : 1.5707963705062866 (25 @ 20bb)

                u3 sub-sub-sub-sub-block { (2a @ 20c0)

                    w : 0.0 (0d @ 20c2)
                    x : 0.0 (15 @ 20c7)
                    y : 0.0 (1d @ 20cc)
                    z : 1.0 (25 @ 20d1)
				}

                u4 sub-sub-sub-sub-block { (32 @ 20d6)

                    x : 15.0 (0d @ 20d8)
                    y : 0.0 (15 @ 20dd)
                    z : 0.0 (1d @ 20e2)
				}
                u5 : 0(38 @ 20e7)

                u6 sub-sub-sub-sub-block { (42 @ 20e9)

                    w : 0.9333333373069763 (0d @ 20eb)
                    x : 0.7111111283302307 (15 @ 20f0)
                    y : 0.8777777552604675 (1d @ 20f5)
                    z : 1.0 (25 @ 20fa)
				}
			}
		}

        component sub-sub-block { (1a @ 20ff)

            component type : SimpleGlow (0a @ 2101)
            number : 102(10 @ 210d)

            simple glow sub-sub-sub-block { (7f2 @ 2110)


                u0 sub-sub-sub-sub-block { (0a @ 2112)

                    w : 0.36707818508148193 (0d @ 2114)
                    x : 0.12029745429754257 (15 @ 2119)
                    y : 0.15514399111270905 (1d @ 211e)
                    z : 0.0 (25 @ 2123)
				}
                u1 : 25.0 (15 @ 2128)
                u2 : 15(18 @ 212d)
                u3 : 15.0 (25 @ 212f)
                u4 : 0.15000000596046448 (2d @ 2134)
                u5 : 0.800000011920929 (35 @ 2139)

                u6 sub-sub-sub-sub-block { (3a @ 213e)

                    y : 0.0 (0d @ 2140)
                    z : 15.0 (15 @ 2145)
				}
			}
		}

        component sub-sub-block { (1a @ 214a)

            component type : CollisionShape (0a @ 214c)
            number : 105(10 @ 215c)

            collision shape sub-sub-sub-block { (3c2 @ 215f)


                u0 sub-sub-sub-sub-block { (0a @ 2161)

                    w : -15.0 (0d @ 2163)
                    x : -8.0 (15 @ 2168)
                    y : 30.0 (1d @ 216d)
                    z : 38.0 (25 @ 2172)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 2178)

                u1 : 1(18 @ 217a)
                w : -40.0 (35 @ 217c)
                x : 40.0 (3d @ 2181)
                y : 3(40 @ 2186)
                z : 1(58 @ 2188)
			}
		}

        position sub-sub-block { (22 @ 218a)

            x position : 0.0 (0d @ 218c)
            y position : 0.0 (15 @ 2191)
		}
        z position : 0.0 (2d @ 2196)
        rotation : 0.0 (35 @ 219b)
        scale : 1.0 (3d @ 21a0)

        u0 sub-sub-block { (42 @ 21a5)

            w : -25.0 (0d @ 21a7)
            x : -25.0 (15 @ 21ac)
            y : 50.0 (1d @ 21b1)
            z : 55.0 (25 @ 21b6)
		}
        hidden : 0(48 @ 21bb)
	}
    u0 : 1.0 (15 @ 21bd)
}

?item block { (12 @ 21c2)


    ?sub-item sub-block { (0a @ 21c5)

        name : item_platearmor (12 @ 21c8)

        component sub-sub-block { (1a @ 21d9)

            component type : PhysicsObject (0a @ 21db)
            number : 1(10 @ 21ea)

            physics object sub-sub-sub-block { (4fa @ 21ed)

                u0 : 1(08 @ 21ef)
                u2 : 0.5 (1d @ 21f1)
                u3 : 1500.0 (25 @ 21f6)
                u4 : 0.0 (2d @ 21fb)
                u5 : 700.0 (35 @ 2200)
                u6 : 0(38 @ 2205)
                u7 : 0.0 (45 @ 2207)
			}
		}

        component sub-sub-block { (1a @ 220c)

            component type : CollectableItem (0a @ 220e)
            number : 2(10 @ 221f)

            collectable item sub-sub-sub-block { (fb2 @ 2222)

                u0 : 0(08 @ 2224)
                u1 : 0(10 @ 2226)

                lua chunk sub-sub-sub-sub-block { (1a @ 2228)

				}
                name :  (22 @ 222a)
                ?model : platearmor (2a @ 222c)
                u0 : 1(30 @ 2238)
			}
		}

        component sub-sub-block { (1a @ 223a)

            component type : ModelTransformController (0a @ 223c)
            number : 3(10 @ 2256)

            model transform controller sub-sub-sub-block { (342 @ 2259)

                u0 : 101(08 @ 225b)
                u2 : 3.1415927410125732 (2d @ 225d)
			}
		}

        component sub-sub-block { (1a @ 2262)

            component type : Model (0a @ 2264)
            number : 101(10 @ 226b)

            3D model sub-sub-sub-block { (32a @ 226e)

                name : item_platearmor (0a @ 2270)
                u0 : 0.0 (15 @ 2281)
                u1 : 1.0 (1d @ 2286)
                u2 : 0.0 (25 @ 228b)

                u3 sub-sub-sub-sub-block { (2a @ 2290)

                    w : 0.0 (0d @ 2292)
                    x : 0.0 (15 @ 2297)
                    y : 0.0 (1d @ 229c)
                    z : 1.0 (25 @ 22a1)
				}

                u4 sub-sub-sub-sub-block { (32 @ 22a6)

                    x : 0.0 (0d @ 22a8)
                    y : -12.0 (15 @ 22ad)
                    z : 0.0 (1d @ 22b2)
				}
                u5 : 0(38 @ 22b7)

                u6 sub-sub-sub-sub-block { (42 @ 22b9)

                    w : 1.0 (0d @ 22bb)
                    x : 1.0 (15 @ 22c0)
                    y : 1.0 (1d @ 22c5)
                    z : 1.0 (25 @ 22ca)
				}
			}
		}

        component sub-sub-block { (1a @ 22cf)

            component type : SimpleGlow (0a @ 22d1)
            number : 102(10 @ 22dd)

            simple glow sub-sub-sub-block { (7f2 @ 22e0)


                u0 sub-sub-sub-sub-block { (0a @ 22e2)

                    w : 0.12263374030590057 (0d @ 22e4)
                    x : 0.18696410953998566 (15 @ 22e9)
                    y : 0.23292176425457 (1d @ 22ee)
                    z : 0.0 (25 @ 22f3)
				}
                u1 : 25.0 (15 @ 22f8)
                u2 : 15(18 @ 22fd)
                u3 : 25.0 (25 @ 22ff)
                u4 : 0.15000000596046448 (2d @ 2304)
                u5 : 0.800000011920929 (35 @ 2309)

                u6 sub-sub-sub-sub-block { (3a @ 230e)

                    y : 0.0 (0d @ 2310)
                    z : 15.0 (15 @ 2315)
				}
			}
		}

        component sub-sub-block { (1a @ 231a)

            component type : CollisionShape (0a @ 231c)
            number : 105(10 @ 232c)

            collision shape sub-sub-sub-block { (3c2 @ 232f)


                u0 sub-sub-sub-sub-block { (0a @ 2331)

                    w : -15.0 (0d @ 2333)
                    x : -8.0 (15 @ 2338)
                    y : 30.0 (1d @ 233d)
                    z : 38.0 (25 @ 2342)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 2348)

                u1 : 1(18 @ 234a)
                w : -40.0 (35 @ 234c)
                x : 40.0 (3d @ 2351)
                y : 3(40 @ 2356)
                z : 1(58 @ 2358)
			}
		}

        position sub-sub-block { (22 @ 235a)

            x position : 0.0 (0d @ 235c)
            y position : 0.0 (15 @ 2361)
		}
        z position : 0.0 (2d @ 2366)
        rotation : 0.0 (35 @ 236b)
        scale : 1.0 (3d @ 2370)

        u0 sub-sub-block { (42 @ 2375)

            w : -25.0 (0d @ 2377)
            x : -25.0 (15 @ 237c)
            y : 50.0 (1d @ 2381)
            z : 55.0 (25 @ 2386)
		}
        hidden : 0(48 @ 238b)
	}
    u0 : 1.5 (15 @ 238d)
}

?item block { (12 @ 2392)


    ?sub-item sub-block { (0a @ 2395)

        name : item_shadowtrinket (12 @ 2398)

        component sub-sub-block { (1a @ 23ac)

            component type : PhysicsObject (0a @ 23ae)
            number : 1(10 @ 23bd)

            physics object sub-sub-sub-block { (4fa @ 23c0)

                u0 : 1(08 @ 23c2)
                u3 : 1500.0 (25 @ 23c4)
                u4 : 0.0 (2d @ 23c9)
                u5 : 700.0 (35 @ 23ce)
                u6 : 0(38 @ 23d3)
                u7 : 0.0 (45 @ 23d5)
			}
		}

        component sub-sub-block { (1a @ 23da)

            component type : CollectableItem (0a @ 23dd)
            number : 2(10 @ 23ee)

            collectable item sub-sub-sub-block { (fb2 @ 23f1)

                u0 : 0(08 @ 23f4)
                u1 : 0(10 @ 23f6)

                lua chunk sub-sub-sub-sub-block { (1a @ 23f8)

                    main chunk : chunk >

                    === lua =============
                    Game.IncCounter("theundead");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00\x1e\x00\x00\x00Game.IncCounter("theundead");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x05\x00\x00\x00\x05\x00\x00\x00\x06@@\x00A\x80\x00\x00\x1c@\x00\x01\x1e\x00\x80\x00\x03\x00\x00\x00\x04\x05\x00\x00\x00Game\x00\x04\x0b\x00\x00\x00IncCounter\x00\x04\n\x00\x00\x00theundead\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 (12 @ 241a)
				}
                name :  (22 @ 24c0)
                ?model : shadowtrinket (2a @ 24c2)
                u0 : 1(30 @ 24d1)
			}
		}

        component sub-sub-block { (1a @ 24d3)

            component type : ModelTransformController (0a @ 24d5)
            number : 3(10 @ 24ef)

            model transform controller sub-sub-sub-block { (342 @ 24f2)

                u0 : 101(08 @ 24f4)
                u2 : 3.1415927410125732 (2d @ 24f6)
			}
		}

        component sub-sub-block { (1a @ 24fb)

            component type : Model (0a @ 24fd)
            number : 101(10 @ 2504)

            3D model sub-sub-sub-block { (32a @ 2507)

                name : item_shadowtrinket (0a @ 2509)
                u0 : 0.0 (15 @ 251d)
                u1 : 5.0 (1d @ 2522)
                u2 : 0.0 (25 @ 2527)

                u3 sub-sub-sub-sub-block { (2a @ 252c)

                    w : 0.0 (0d @ 252e)
                    x : 0.0 (15 @ 2533)
                    y : 0.0 (1d @ 2538)
                    z : 1.0 (25 @ 253d)
				}

                u4 sub-sub-sub-sub-block { (32 @ 2542)

                    x : 0.0 (0d @ 2544)
                    y : -15.0 (15 @ 2549)
                    z : 0.0 (1d @ 254e)
				}
                u5 : 0(38 @ 2553)

                u6 sub-sub-sub-sub-block { (42 @ 2555)

                    w : 1.0 (0d @ 2557)
                    x : 1.0 (15 @ 255c)
                    y : 1.0 (1d @ 2561)
                    z : 1.0 (25 @ 2566)
				}
			}
		}

        component sub-sub-block { (1a @ 256b)

            component type : SimpleGlow (0a @ 256d)
            number : 102(10 @ 2579)

            simple glow sub-sub-sub-block { (7f2 @ 257c)


                u0 sub-sub-sub-sub-block { (0a @ 257e)

                    w : 1.0 (0d @ 2580)
                    x : 0.3444444537162781 (15 @ 2585)
                    y : 1.0 (1d @ 258a)
                    z : 0.6333333253860474 (25 @ 258f)
				}
                u1 : 25.0 (15 @ 2594)
                u2 : 16(18 @ 2599)
                u3 : 15.0 (25 @ 259b)
                u4 : 0.15000000596046448 (2d @ 25a0)
                u5 : 1.2000000476837158 (35 @ 25a5)

                u6 sub-sub-sub-sub-block { (3a @ 25aa)

                    y : 0.0 (0d @ 25ac)
                    z : 14.0 (15 @ 25b1)
				}
			}
		}

        component sub-sub-block { (1a @ 25b6)

            component type : CollisionShape (0a @ 25b8)
            number : 105(10 @ 25c8)

            collision shape sub-sub-sub-block { (3c2 @ 25cb)


                u0 sub-sub-sub-sub-block { (0a @ 25cd)

                    w : -5.0 (0d @ 25cf)
                    x : 0.0 (15 @ 25d4)
                    y : 10.0 (1d @ 25d9)
                    z : 30.0 (25 @ 25de)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 25e4)

                u1 : 1(18 @ 25e6)
                w : -40.0 (35 @ 25e8)
                x : 40.0 (3d @ 25ed)
                y : 3(40 @ 25f2)
                z : 1(58 @ 25f4)
			}
		}

        position sub-sub-block { (22 @ 25f6)

            x position : 0.0 (0d @ 25f8)
            y position : 0.0 (15 @ 25fd)
		}
        z position : 0.0 (2d @ 2602)
        rotation : 0.0 (35 @ 2607)
        scale : 1.0 (3d @ 260c)

        u0 sub-sub-block { (42 @ 2611)

            w : -25.0 (0d @ 2613)
            x : -25.0 (15 @ 2618)
            y : 50.0 (1d @ 261d)
            z : 55.0 (25 @ 2622)
		}
        hidden : 0(48 @ 2627)
	}
    u0 : 1.0 (15 @ 2629)
}

?item block { (12 @ 262e)


    ?sub-item sub-block { (0a @ 2631)

        name : item_thorn (12 @ 2634)

        component sub-sub-block { (1a @ 2640)

            component type : PhysicsObject (0a @ 2642)
            number : 1(10 @ 2651)

            physics object sub-sub-sub-block { (4fa @ 2654)

                u0 : 1(08 @ 2656)
                u2 : 0.800000011920929 (1d @ 2658)
                u3 : 1500.0 (25 @ 265d)
                u4 : 0.0 (2d @ 2662)
                u5 : 700.0 (35 @ 2667)
                u6 : 0(38 @ 266c)
                u7 : 0.0 (45 @ 266e)
			}
		}

        component sub-sub-block { (1a @ 2673)

            component type : CollectableItem (0a @ 2676)
            number : 2(10 @ 2687)

            collectable item sub-sub-sub-block { (fb2 @ 268a)

                u0 : 0(08 @ 268d)
                u1 : 0(10 @ 268f)

                lua chunk sub-sub-sub-sub-block { (1a @ 2691)

                    main chunk : chunk >

                    === lua =============
                    Game.IncCounter("anotherentrance");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00$\x00\x00\x00Game.IncCounter("anotherentrance");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x05\x00\x00\x00\x05\x00\x00\x00\x06@@\x00A\x80\x00\x00\x1c@\x00\x01\x1e\x00\x80\x00\x03\x00\x00\x00\x04\x05\x00\x00\x00Game\x00\x04\x0b\x00\x00\x00IncCounter\x00\x04\x10\x00\x00\x00anotherentrance\x00\x00\x00\x00\x00\x05\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 (12 @ 26b9)
				}
                name :  (22 @ 276b)
                ?model : thorn (2a @ 276d)
                u0 : 1(30 @ 2774)
			}
		}

        component sub-sub-block { (1a @ 2776)

            component type : ModelTransformController (0a @ 2778)
            number : 3(10 @ 2792)

            model transform controller sub-sub-sub-block { (342 @ 2795)

                u0 : 101(08 @ 2797)
                u2 : 3.1415927410125732 (2d @ 2799)
			}
		}

        component sub-sub-block { (1a @ 279e)

            component type : Model (0a @ 27a0)
            number : 101(10 @ 27a7)

            3D model sub-sub-sub-block { (32a @ 27aa)

                name : weapon_broadsword (0a @ 27ac)
                u0 : 0.7853981852531433 (15 @ 27bf)
                u1 : 1.0 (1d @ 27c4)
                u2 : 1.5707963705062866 (25 @ 27c9)

                u3 sub-sub-sub-sub-block { (2a @ 27ce)

                    w : 0.0 (0d @ 27d0)
                    x : 0.0 (15 @ 27d5)
                    y : 0.0 (1d @ 27da)
                    z : 1.0 (25 @ 27df)
				}

                u4 sub-sub-sub-sub-block { (32 @ 27e4)

                    x : 10.0 (0d @ 27e6)
                    y : -7.0 (15 @ 27eb)
                    z : 0.0 (1d @ 27f0)
				}
                u5 : 0(38 @ 27f5)

                u6 sub-sub-sub-sub-block { (42 @ 27f7)

                    w : 0.6777777671813965 (0d @ 27f9)
                    x : 1.0 (15 @ 27fe)
                    y : 0.644444465637207 (1d @ 2803)
                    z : 1.0 (25 @ 2808)
				}
			}
		}

        component sub-sub-block { (1a @ 280d)

            component type : SimpleGlow (0a @ 280f)
            number : 102(10 @ 281b)

            simple glow sub-sub-sub-block { (7f2 @ 281e)


                u0 sub-sub-sub-sub-block { (0a @ 2820)

                    w : 0.12263374030590057 (0d @ 2822)
                    x : 0.18696410953998566 (15 @ 2827)
                    y : 0.23292176425457 (1d @ 282c)
                    z : 0.0 (25 @ 2831)
				}
                u1 : 25.0 (15 @ 2836)
                u2 : 15(18 @ 283b)
                u3 : 15.0 (25 @ 283d)
                u4 : 0.15000000596046448 (2d @ 2842)
                u5 : 0.800000011920929 (35 @ 2847)

                u6 sub-sub-sub-sub-block { (3a @ 284c)

                    y : 0.0 (0d @ 284e)
                    z : 15.0 (15 @ 2853)
				}
			}
		}

        component sub-sub-block { (1a @ 2858)

            component type : CollisionShape (0a @ 285a)
            number : 105(10 @ 286a)

            collision shape sub-sub-sub-block { (3c2 @ 286d)


                u0 sub-sub-sub-sub-block { (0a @ 286f)

                    w : -15.0 (0d @ 2871)
                    x : -8.0 (15 @ 2876)
                    y : 30.0 (1d @ 287b)
                    z : 38.0 (25 @ 2880)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 2886)

                u1 : 1(18 @ 2888)
                w : -40.0 (35 @ 288a)
                x : 40.0 (3d @ 288f)
                y : 3(40 @ 2894)
                z : 1(58 @ 2896)
			}
		}

        position sub-sub-block { (22 @ 2898)

            x position : 0.0 (0d @ 289a)
            y position : 0.0 (15 @ 289f)
		}
        z position : 0.0 (2d @ 28a4)
        rotation : 0.0 (35 @ 28a9)
        scale : 1.0 (3d @ 28ae)

        u0 sub-sub-block { (42 @ 28b3)

            w : -25.0 (0d @ 28b5)
            x : -25.0 (15 @ 28ba)
            y : 50.0 (1d @ 28bf)
            z : 55.0 (25 @ 28c4)
		}
        hidden : 0(48 @ 28c9)
	}
    u0 : 1.0 (15 @ 28cb)
}

?item block { (12 @ 28d0)


    ?sub-item sub-block { (0a @ 28d3)

        name : manabottle (12 @ 28d6)

        component sub-sub-block { (1a @ 28e2)

            component type : PhysicsObject (0a @ 28e4)
            number : 1(10 @ 28f3)

            physics object sub-sub-sub-block { (4fa @ 28f6)

                u0 : 1(08 @ 28f8)
                u3 : 1500.0 (25 @ 28fa)
                u4 : 0.0 (2d @ 28ff)
                u5 : 700.0 (35 @ 2904)
                u6 : 0(38 @ 2909)
                u7 : 0.0 (45 @ 290b)
			}
		}

        component sub-sub-block { (1a @ 2910)

            component type : Model (0a @ 2912)
            number : 101(10 @ 2919)

            3D model sub-sub-sub-block { (32a @ 291c)

                name : manabottle (0a @ 291e)
                u0 : 0.0 (15 @ 292a)
                u1 : 1.5 (1d @ 292f)
                u2 : 0.0 (25 @ 2934)

                u3 sub-sub-sub-sub-block { (2a @ 2939)

                    w : 0.0 (0d @ 293b)
                    x : 0.0 (15 @ 2940)
                    y : 0.0 (1d @ 2945)
                    z : 1.0 (25 @ 294a)
				}

                u4 sub-sub-sub-sub-block { (32 @ 294f)

                    x : 0.0 (0d @ 2951)
                    y : 0.0 (15 @ 2956)
                    z : 0.0 (1d @ 295b)
				}
                u5 : 0(38 @ 2960)

                u6 sub-sub-sub-sub-block { (42 @ 2962)

                    w : 1.0 (0d @ 2964)
                    x : 1.0 (15 @ 2969)
                    y : 1.0 (1d @ 296e)
                    z : 1.0 (25 @ 2973)
				}
			}
		}

        component sub-sub-block { (1a @ 2978)

            component type : SimpleGlow (0a @ 297a)
            number : 102(10 @ 2986)

            simple glow sub-sub-sub-block { (7f2 @ 2989)


                u0 sub-sub-sub-sub-block { (0a @ 298b)

                    w : 0.0 (0d @ 298d)
                    x : 0.4000000059604645 (15 @ 2992)
                    y : 0.800000011920929 (1d @ 2997)
                    z : 0.0 (25 @ 299c)
				}
                u1 : 16.0 (15 @ 29a1)
                u2 : 10(18 @ 29a6)
                u3 : 5.0 (25 @ 29a8)
                u4 : 0.15000000596046448 (2d @ 29ad)
                u5 : 0.800000011920929 (35 @ 29b2)

                u6 sub-sub-sub-sub-block { (3a @ 29b7)

                    y : 0.0 (0d @ 29b9)
                    z : 0.0 (15 @ 29be)
				}
			}
		}

        component sub-sub-block { (1a @ 29c3)

            component type : CollisionShape (0a @ 29c5)
            number : 104(10 @ 29d5)

            collision shape sub-sub-sub-block { (3c2 @ 29d8)


                u0 sub-sub-sub-sub-block { (0a @ 29da)

                    w : -10.0 (0d @ 29dc)
                    x : -10.0 (15 @ 29e1)
                    y : 20.0 (1d @ 29e6)
                    z : 20.0 (25 @ 29eb)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 29f1)

                u1 : 1(18 @ 29f3)
                w : -15.0 (35 @ 29f5)
                x : 15.0 (3d @ 29fa)
                y : 3(40 @ 29ff)
                z : 1(58 @ 2a01)
			}
		}

        component sub-sub-block { (1a @ 2a03)

            component type : CollectableItem (0a @ 2a05)
            number : 107(10 @ 2a16)

            collectable item sub-sub-sub-block { (fb2 @ 2a19)

                u0 : 2(08 @ 2a1b)
                u1 : 20(10 @ 2a1d)

                lua chunk sub-sub-sub-sub-block { (1a @ 2a1f)

				}
                name :  (22 @ 2a21)
                ?model :  (2a @ 2a23)
                u0 : 0(30 @ 2a25)
			}
		}

        position sub-sub-block { (22 @ 2a27)

            x position : 0.0 (0d @ 2a29)
            y position : 0.0 (15 @ 2a2e)
		}
        z position : 0.0 (2d @ 2a33)
        rotation : 0.0 (35 @ 2a38)
        scale : 1.0 (3d @ 2a3d)

        u0 sub-sub-block { (42 @ 2a42)

            w : -16.0 (0d @ 2a44)
            x : -16.0 (15 @ 2a49)
            y : 32.0 (1d @ 2a4e)
            z : 32.0 (25 @ 2a53)
		}
        hidden : 0(48 @ 2a58)
	}
    u0 : 1.0 (15 @ 2a5a)
}

?item block { (12 @ 2a5f)


    ?sub-item sub-block { (0a @ 2a62)

        name : manabottle_big (12 @ 2a65)

        component sub-sub-block { (1a @ 2a75)

            component type : PhysicsObject (0a @ 2a77)
            number : 1(10 @ 2a86)

            physics object sub-sub-sub-block { (4fa @ 2a89)

                u0 : 1(08 @ 2a8b)
                u3 : 1500.0 (25 @ 2a8d)
                u4 : 0.0 (2d @ 2a92)
                u5 : 700.0 (35 @ 2a97)
                u6 : 0(38 @ 2a9c)
                u7 : 0.0 (45 @ 2a9e)
			}
		}

        component sub-sub-block { (1a @ 2aa3)

            component type : Model (0a @ 2aa5)
            number : 101(10 @ 2aac)

            3D model sub-sub-sub-block { (32a @ 2aaf)

                name : manabottlebig (0a @ 2ab1)
                u0 : 0.0 (15 @ 2ac0)
                u1 : 1.5 (1d @ 2ac5)
                u2 : 0.0 (25 @ 2aca)

                u3 sub-sub-sub-sub-block { (2a @ 2acf)

                    w : 0.0 (0d @ 2ad1)
                    x : 0.0 (15 @ 2ad6)
                    y : 0.0 (1d @ 2adb)
                    z : 1.0 (25 @ 2ae0)
				}

                u4 sub-sub-sub-sub-block { (32 @ 2ae5)

                    x : 0.0 (0d @ 2ae7)
                    y : 0.0 (15 @ 2aec)
                    z : 0.0 (1d @ 2af1)
				}
                u5 : 0(38 @ 2af6)

                u6 sub-sub-sub-sub-block { (42 @ 2af8)

                    w : 1.0 (0d @ 2afa)
                    x : 1.0 (15 @ 2aff)
                    y : 1.0 (1d @ 2b04)
                    z : 1.0 (25 @ 2b09)
				}
			}
		}

        component sub-sub-block { (1a @ 2b0e)

            component type : SimpleGlow (0a @ 2b10)
            number : 102(10 @ 2b1c)

            simple glow sub-sub-sub-block { (7f2 @ 2b1f)


                u0 sub-sub-sub-sub-block { (0a @ 2b21)

                    w : 0.0 (0d @ 2b23)
                    x : 0.4000000059604645 (15 @ 2b28)
                    y : 0.800000011920929 (1d @ 2b2d)
                    z : 0.0 (25 @ 2b32)
				}
                u1 : 21.0 (15 @ 2b37)
                u2 : 10(18 @ 2b3c)
                u3 : 5.0 (25 @ 2b3e)
                u4 : 0.15000000596046448 (2d @ 2b43)
                u5 : 0.800000011920929 (35 @ 2b48)

                u6 sub-sub-sub-sub-block { (3a @ 2b4d)

                    y : 0.0 (0d @ 2b4f)
                    z : 0.0 (15 @ 2b54)
				}
			}
		}

        component sub-sub-block { (1a @ 2b59)

            component type : CollisionShape (0a @ 2b5b)
            number : 104(10 @ 2b6b)

            collision shape sub-sub-sub-block { (3c2 @ 2b6e)


                u0 sub-sub-sub-sub-block { (0a @ 2b70)

                    w : -12.0 (0d @ 2b72)
                    x : -12.0 (15 @ 2b77)
                    y : 24.0 (1d @ 2b7c)
                    z : 24.0 (25 @ 2b81)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 2b87)

                u1 : 1(18 @ 2b89)
                w : -15.0 (35 @ 2b8b)
                x : 15.0 (3d @ 2b90)
                y : 3(40 @ 2b95)
                z : 1(58 @ 2b97)
			}
		}

        component sub-sub-block { (1a @ 2b99)

            component type : CollectableItem (0a @ 2b9b)
            number : 107(10 @ 2bac)

            collectable item sub-sub-sub-block { (fb2 @ 2baf)

                u0 : 2(08 @ 2bb1)
                u1 : 100(10 @ 2bb3)

                lua chunk sub-sub-sub-sub-block { (1a @ 2bb5)

				}
                name :  (22 @ 2bb7)
                ?model :  (2a @ 2bb9)
                u0 : 0(30 @ 2bbb)
			}
		}

        position sub-sub-block { (22 @ 2bbd)

            x position : 0.0 (0d @ 2bbf)
            y position : 0.0 (15 @ 2bc4)
		}
        z position : 0.0 (2d @ 2bc9)
        rotation : 0.0 (35 @ 2bce)
        scale : 1.0 (3d @ 2bd3)

        u0 sub-sub-block { (42 @ 2bd8)

            w : -21.0 (0d @ 2bda)
            x : -21.0 (15 @ 2bdf)
            y : 42.0 (1d @ 2be4)
            z : 42.0 (25 @ 2be9)
		}
        hidden : 0(48 @ 2bee)
	}
    u0 : 1.0 (15 @ 2bf0)
}

?item block { (12 @ 2bf5)


    ?sub-item sub-block { (0a @ 2bf8)

        name : nugget_health (12 @ 2bfb)

        component sub-sub-block { (1a @ 2c0a)

            component type : ParticleEmitter (0a @ 2c0d)
            number : 1(10 @ 2c1e)

            particle emitter sub-sub-sub-block { (7d2 @ 2c21)

                particle : 2(10 @ 2c24)
                particle : 3(10 @ 2c26)
                particle : 4(10 @ 2c28)
                u1 : 0(18 @ 2c2a)
                u2 : 15(20 @ 2c2c)
                u3 : 0(28 @ 2c2e)
                u4 : 0(30 @ 2c30)

                u5 sub-sub-sub-sub-block { (3a @ 2c32)

                    u0 : 5(08 @ 2c35)

                    u1 sub-sub-sub-sub-sub-block { (12 @ 2c37)

                        w : 0.3720988631248474 (0d @ 2c39)
                        x : 0.11679011583328247 (15 @ 2c3e)
                        y : 0.11679020524024963 (1d @ 2c43)
                        z : 0.22222226858139038 (25 @ 2c48)
					}
                    u2 : 90.0 (1d @ 2c4d)
                    u2 : 0.0 (1d @ 2c52)
                    u2 : 0.0 (1d @ 2c57)
                    u2 : 11.0 (1d @ 2c5c)
                    u2 : 0.0 (1d @ 2c61)
                    u2 : 25.0 (1d @ 2c66)
                    u2 : 0.0 (1d @ 2c6b)
                    u2 : 0.0 (1d @ 2c70)
                    u2 : 0.3499999940395355 (1d @ 2c75)
                    u2 : 1.0 (1d @ 2c7a)
                    u2 : 0.0 (1d @ 2c7f)
                    u2 : 0.05000000074505806 (1d @ 2c84)
                    u2 : 0.6000000238418579 (1d @ 2c89)
                    u2 : 0.0 (1d @ 2c8e)
                    u2 : 0.0 (1d @ 2c93)
                    u3 : 0.0 (25 @ 2c98)
                    u4 : 0.0 (2d @ 2c9d)
                    u5 : 0.0 (35 @ 2ca2)

                    u6 sub-sub-sub-sub-sub-block { (3a @ 2ca7)

                        u0 : 0.0 (0d @ 2ca9)
                        u1 : -3.0 (15 @ 2cae)
                        u2 : 0.0 (1d @ 2cb3)
					}
				}
                u6 : 1(40 @ 2cb8)
			}
		}

        component sub-sub-block { (1a @ 2cba)

            component type : Particle (0a @ 2cbc)
            number : 2(10 @ 2cc6)

            particle sub-sub-sub-block { (7da @ 2cc9)

                name : particle_fure_1 (0a @ 2ccb)
                u0 : 40.0 (15 @ 2cdc)
			}
		}

        component sub-sub-block { (1a @ 2ce1)

            component type : Particle (0a @ 2ce3)
            number : 3(10 @ 2ced)

            particle sub-sub-sub-block { (7da @ 2cf0)

                name : particle_fure_2 (0a @ 2cf2)
                u0 : 40.0 (15 @ 2d03)
			}
		}

        component sub-sub-block { (1a @ 2d08)

            component type : Particle (0a @ 2d0a)
            number : 4(10 @ 2d14)

            particle sub-sub-sub-block { (7da @ 2d17)

                name : particle_fure_3 (0a @ 2d19)
                u0 : 40.0 (15 @ 2d2a)
			}
		}

        component sub-sub-block { (1a @ 2d2f)

            component type : Model (0a @ 2d31)
            number : 101(10 @ 2d38)

            3D model sub-sub-sub-block { (32a @ 2d3b)

                name : nugget_health (0a @ 2d3d)
                u0 : 0.0 (15 @ 2d4c)
                u1 : 5.0 (1d @ 2d51)
                u2 : 0.0 (25 @ 2d56)

                u3 sub-sub-sub-sub-block { (2a @ 2d5b)

                    w : 1.0 (0d @ 2d5d)
                    x : 1.0 (15 @ 2d62)
                    y : 1.0 (1d @ 2d67)
                    z : 1.0 (25 @ 2d6c)
				}

                u4 sub-sub-sub-sub-block { (32 @ 2d71)

                    x : 0.0 (0d @ 2d73)
                    y : 0.0 (15 @ 2d78)
                    z : 0.0 (1d @ 2d7d)
				}
                u5 : 0(38 @ 2d82)

                u6 sub-sub-sub-sub-block { (42 @ 2d84)

                    w : 1.0 (0d @ 2d86)
                    x : 1.0 (15 @ 2d8b)
                    y : 1.0 (1d @ 2d90)
                    z : 1.0 (25 @ 2d95)
				}
			}
		}

        component sub-sub-block { (1a @ 2d9a)

            component type : SimpleGlow (0a @ 2d9c)
            number : 102(10 @ 2da8)

            simple glow sub-sub-sub-block { (7f2 @ 2dab)


                u0 sub-sub-sub-sub-block { (0a @ 2dad)

                    w : 1.0 (0d @ 2daf)
                    x : 0.5 (15 @ 2db4)
                    y : 0.5 (1d @ 2db9)
                    z : 0.0 (25 @ 2dbe)
				}
                u1 : 12.0 (15 @ 2dc3)
                u2 : 10(18 @ 2dc8)
                u3 : 0.0 (25 @ 2dca)
                u4 : 0.15000000596046448 (2d @ 2dcf)
                u5 : 0.800000011920929 (35 @ 2dd4)

                u6 sub-sub-sub-sub-block { (3a @ 2dd9)

                    y : 0.0 (0d @ 2ddb)
                    z : 0.0 (15 @ 2de0)
				}
			}
		}

        component sub-sub-block { (1a @ 2de5)

            component type : CollectableItem (0a @ 2de8)
            number : 104(10 @ 2df9)

            collectable item sub-sub-sub-block { (fb2 @ 2dfc)

                u0 : 1(08 @ 2dff)
                u1 : 2(10 @ 2e01)

                lua chunk sub-sub-sub-sub-block { (1a @ 2e03)

                    main chunk : chunk >

                    === lua =============
                    local self = ...;
                    Scene.CreateObject("collect_health", "", self);

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00C\x00\x00\x00local self = ...;\r\nScene.CreateObject("collect_health", "", self);\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x05\x08\x00\x00\x00%\x00\x00\x01E\x00\x00\x00F@\xc0\x00\x81\x80\x00\x00\xc1\xc0\x00\x00\x00\x01\x00\x00\\@\x00\x02\x1e\x00\x80\x00\x04\x00\x00\x00\x04\x06\x00\x00\x00Scene\x00\x04\r\x00\x00\x00CreateObject\x00\x04\x0f\x00\x00\x00collect_health\x00\x04\x01\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00self\x00\x01\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00 (12 @ 2e4a)
				}
                name :  (22 @ 2f4c)
                ?model :  (2a @ 2f4e)
                u0 : 0(30 @ 2f50)
			}
		}

        component sub-sub-block { (1a @ 2f52)

            component type : CollisionShape (0a @ 2f54)
            number : 105(10 @ 2f64)

            collision shape sub-sub-sub-block { (3c2 @ 2f67)


                u0 sub-sub-sub-sub-block { (0a @ 2f69)

                    w : -6.0 (0d @ 2f6b)
                    x : -7.0 (15 @ 2f70)
                    y : 12.0 (1d @ 2f75)
                    z : 27.0 (25 @ 2f7a)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 2f80)

                u1 : 1(18 @ 2f82)
                w : -15.0 (35 @ 2f84)
                x : 15.0 (3d @ 2f89)
                y : 3(40 @ 2f8e)
                z : 1(58 @ 2f90)
			}
		}

        component sub-sub-block { (1a @ 2f92)

            component type : PhysicsObject (0a @ 2f94)
            number : 107(10 @ 2fa3)

            physics object sub-sub-sub-block { (4fa @ 2fa6)

                u0 : 1(08 @ 2fa8)
                u3 : 1500.0 (25 @ 2faa)
                u4 : 0.0 (2d @ 2faf)
                u5 : 700.0 (35 @ 2fb4)
                u6 : 0(38 @ 2fb9)
                u7 : 0.0 (45 @ 2fbb)
			}
		}

        position sub-sub-block { (22 @ 2fc0)

            x position : 0.0 (0d @ 2fc2)
            y position : 0.0 (15 @ 2fc7)
		}
        z position : 0.0 (2d @ 2fcc)
        rotation : 0.0 (35 @ 2fd1)
        scale : 1.0 (3d @ 2fd6)

        u0 sub-sub-block { (42 @ 2fdb)

            w : -12.0 (0d @ 2fdd)
            x : -12.0 (15 @ 2fe2)
            y : 24.0 (1d @ 2fe7)
            z : 32.0 (25 @ 2fec)
		}
        hidden : 0(48 @ 2ff1)
	}
    u0 : 1.0 (15 @ 2ff3)
}

?item block { (12 @ 2ff8)


    ?sub-item sub-block { (0a @ 2ffb)

        name : nugget_mana (12 @ 2ffe)

        component sub-sub-block { (1a @ 300b)

            component type : ParticleEmitter (0a @ 300e)
            number : 1(10 @ 301f)

            particle emitter sub-sub-sub-block { (7d2 @ 3022)

                particle : 2(10 @ 3025)
                particle : 3(10 @ 3027)
                particle : 4(10 @ 3029)
                u1 : 0(18 @ 302b)
                u2 : 15(20 @ 302d)
                u3 : 0(28 @ 302f)
                u4 : 0(30 @ 3031)

                u5 sub-sub-sub-sub-block { (3a @ 3033)

                    u0 : 5(08 @ 3036)

                    u1 sub-sub-sub-sub-sub-block { (12 @ 3038)

                        w : 0.0 (0d @ 303a)
                        x : 0.24000000953674316 (15 @ 303f)
                        y : 0.6000000834465027 (1d @ 3044)
                        z : 0.2777777910232544 (25 @ 3049)
					}
                    u2 : 90.0 (1d @ 304e)
                    u2 : 0.0 (1d @ 3053)
                    u2 : 0.0 (1d @ 3058)
                    u2 : 11.0 (1d @ 305d)
                    u2 : 0.0 (1d @ 3062)
                    u2 : 20.0 (1d @ 3067)
                    u2 : 0.0 (1d @ 306c)
                    u2 : 0.0 (1d @ 3071)
                    u2 : 0.3499999940395355 (1d @ 3076)
                    u2 : 1.0 (1d @ 307b)
                    u2 : 0.0 (1d @ 3080)
                    u2 : 0.05000000074505806 (1d @ 3085)
                    u2 : 0.6000000238418579 (1d @ 308a)
                    u2 : 0.0 (1d @ 308f)
                    u2 : 0.0 (1d @ 3094)
                    u3 : 0.0 (25 @ 3099)
                    u4 : 0.0 (2d @ 309e)
                    u5 : 0.0 (35 @ 30a3)

                    u6 sub-sub-sub-sub-sub-block { (3a @ 30a8)

                        u0 : 0.0 (0d @ 30aa)
                        u1 : -3.0 (15 @ 30af)
                        u2 : 0.0 (1d @ 30b4)
					}
				}
                u6 : 1(40 @ 30b9)
			}
		}

        component sub-sub-block { (1a @ 30bb)

            component type : Particle (0a @ 30bd)
            number : 2(10 @ 30c7)

            particle sub-sub-sub-block { (7da @ 30ca)

                name : particle_fure_1 (0a @ 30cc)
                u0 : 40.0 (15 @ 30dd)
			}
		}

        component sub-sub-block { (1a @ 30e2)

            component type : Particle (0a @ 30e4)
            number : 3(10 @ 30ee)

            particle sub-sub-sub-block { (7da @ 30f1)

                name : particle_fure_2 (0a @ 30f3)
                u0 : 40.0 (15 @ 3104)
			}
		}

        component sub-sub-block { (1a @ 3109)

            component type : Particle (0a @ 310b)
            number : 4(10 @ 3115)

            particle sub-sub-sub-block { (7da @ 3118)

                name : particle_fure_3 (0a @ 311a)
                u0 : 40.0 (15 @ 312b)
			}
		}

        component sub-sub-block { (1a @ 3130)

            component type : Model (0a @ 3132)
            number : 101(10 @ 3139)

            3D model sub-sub-sub-block { (32a @ 313c)

                name : nugget_mana (0a @ 313e)
                u0 : 0.0 (15 @ 314b)
                u1 : 5.0 (1d @ 3150)
                u2 : 0.0 (25 @ 3155)

                u3 sub-sub-sub-sub-block { (2a @ 315a)

                    w : 1.0 (0d @ 315c)
                    x : 1.0 (15 @ 3161)
                    y : 1.0 (1d @ 3166)
                    z : 1.0 (25 @ 316b)
				}

                u4 sub-sub-sub-sub-block { (32 @ 3170)

                    x : 0.0 (0d @ 3172)
                    y : 0.0 (15 @ 3177)
                    z : 0.0 (1d @ 317c)
				}
                u5 : 0(38 @ 3181)

                u6 sub-sub-sub-sub-block { (42 @ 3183)

                    w : 1.0 (0d @ 3185)
                    x : 1.0 (15 @ 318a)
                    y : 1.0 (1d @ 318f)
                    z : 1.0 (25 @ 3194)
				}
			}
		}

        component sub-sub-block { (1a @ 3199)

            component type : SimpleGlow (0a @ 319b)
            number : 102(10 @ 31a7)

            simple glow sub-sub-sub-block { (7f2 @ 31aa)


                u0 sub-sub-sub-sub-block { (0a @ 31ac)

                    w : 0.5 (0d @ 31ae)
                    x : 0.5 (15 @ 31b3)
                    y : 1.0 (1d @ 31b8)
                    z : 0.0 (25 @ 31bd)
				}
                u1 : 12.0 (15 @ 31c2)
                u2 : 10(18 @ 31c7)
                u3 : 0.0 (25 @ 31c9)
                u4 : 0.15000000596046448 (2d @ 31ce)
                u5 : 0.800000011920929 (35 @ 31d3)

                u6 sub-sub-sub-sub-block { (3a @ 31d8)

                    y : 0.0 (0d @ 31da)
                    z : 0.0 (15 @ 31df)
				}
			}
		}

        component sub-sub-block { (1a @ 31e4)

            component type : CollectableItem (0a @ 31e7)
            number : 104(10 @ 31f8)

            collectable item sub-sub-sub-block { (fb2 @ 31fb)

                u0 : 2(08 @ 31fe)
                u1 : 20(10 @ 3200)

                lua chunk sub-sub-sub-sub-block { (1a @ 3202)

                    main chunk : chunk >

                    === lua =============
                    local self = ...;
                    Scene.CreateObject("collect_mana", "", self);
                    SoundLibrary.PlayEffect("managet");

                    =====================
                    secondary chunk : \x1bLuaQ\x00\x01\x04\x04\x04\x08\x00f\x00\x00\x00local self = ...;\r\nScene.CreateObject("collect_mana", "", self);\r\nSoundLibrary.PlayEffect("managet");\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x05\x0c\x00\x00\x00%\x00\x00\x01E\x00\x00\x00F@\xc0\x00\x81\x80\x00\x00\xc1\xc0\x00\x00\x00\x01\x00\x00\\@\x00\x02E\x00\x01\x00F@\xc1\x00\x81\x80\x01\x00\\@\x00\x01\x1e\x00\x80\x00\x07\x00\x00\x00\x04\x06\x00\x00\x00Scene\x00\x04\r\x00\x00\x00CreateObject\x00\x04\r\x00\x00\x00collect_mana\x00\x04\x01\x00\x00\x00\x00\x04\r\x00\x00\x00SoundLibrary\x00\x04\x0b\x00\x00\x00PlayEffect\x00\x04\x08\x00\x00\x00managet\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x01\x00\x00\x00\x05\x00\x00\x00self\x00\x01\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00 (12 @ 326c)
				}
                name :  (22 @ 33de)
                ?model :  (2a @ 33e0)
                u0 : 0(30 @ 33e2)
			}
		}

        component sub-sub-block { (1a @ 33e4)

            component type : CollisionShape (0a @ 33e6)
            number : 105(10 @ 33f6)

            collision shape sub-sub-sub-block { (3c2 @ 33f9)


                u0 sub-sub-sub-sub-block { (0a @ 33fb)

                    w : -6.0 (0d @ 33fd)
                    x : -7.0 (15 @ 3402)
                    y : 12.0 (1d @ 3407)
                    z : 27.0 (25 @ 340c)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 3412)

                u1 : 1(18 @ 3414)
                w : -15.0 (35 @ 3416)
                x : 15.0 (3d @ 341b)
                y : 3(40 @ 3420)
                z : 1(58 @ 3422)
			}
		}

        component sub-sub-block { (1a @ 3424)

            component type : PhysicsObject (0a @ 3426)
            number : 107(10 @ 3435)

            physics object sub-sub-sub-block { (4fa @ 3438)

                u0 : 1(08 @ 343a)
                u3 : 1500.0 (25 @ 343c)
                u4 : 0.0 (2d @ 3441)
                u5 : 700.0 (35 @ 3446)
                u6 : 0(38 @ 344b)
                u7 : 0.0 (45 @ 344d)
			}
		}

        position sub-sub-block { (22 @ 3452)

            x position : 0.0 (0d @ 3454)
            y position : 0.0 (15 @ 3459)
		}
        z position : 0.0 (2d @ 345e)
        rotation : 0.0 (35 @ 3463)
        scale : 1.0 (3d @ 3468)

        u0 sub-sub-block { (42 @ 346d)

            w : -12.0 (0d @ 346f)
            x : -12.0 (15 @ 3474)
            y : 24.0 (1d @ 3479)
            z : 32.0 (25 @ 347e)
		}
        hidden : 0(48 @ 3483)
	}
    u0 : 1.0 (15 @ 3485)
}

?item block { (12 @ 348a)


    ?sub-item sub-block { (0a @ 348d)

        name : powershard (12 @ 3490)

        component sub-sub-block { (1a @ 349c)

            component type : PhysicsObject (0a @ 349e)
            number : 1(10 @ 34ad)

            physics object sub-sub-sub-block { (4fa @ 34b0)

                u0 : 1(08 @ 34b2)

                u1 sub-sub-sub-sub-block { (12 @ 34b4)

                    u0 : 0.009999500587582588 (0d @ 34b6)
                    u1 : 0.9999500513076782 (15 @ 34bb)
				}
                u2 : 0.009999999776482582 (1d @ 34c0)
                u3 : 1500.0 (25 @ 34c5)
                u4 : 0.0 (2d @ 34ca)
                u5 : 700.0 (35 @ 34cf)
                u6 : 0(38 @ 34d4)
                u7 : 0.0 (45 @ 34d6)
			}
		}

        component sub-sub-block { (1a @ 34db)

            component type : Model (0a @ 34dd)
            number : 101(10 @ 34e4)

            3D model sub-sub-sub-block { (32a @ 34e7)

                name : powershard (0a @ 34e9)
                u0 : 0.0 (15 @ 34f5)
                u1 : 5.0 (1d @ 34fa)
                u2 : 0.0 (25 @ 34ff)

                u3 sub-sub-sub-sub-block { (2a @ 3504)

                    w : 0.0 (0d @ 3506)
                    x : 0.0 (15 @ 350b)
                    y : 0.0 (1d @ 3510)
                    z : 1.0 (25 @ 3515)
				}

                u4 sub-sub-sub-sub-block { (32 @ 351a)

                    x : 0.0 (0d @ 351c)
                    y : 0.0 (15 @ 3521)
                    z : 0.0 (1d @ 3526)
				}
                u5 : 0(38 @ 352b)

                u6 sub-sub-sub-sub-block { (42 @ 352d)

                    w : 1.0 (0d @ 352f)
                    x : 1.0 (15 @ 3534)
                    y : 1.0 (1d @ 3539)
                    z : 1.0 (25 @ 353e)
				}
			}
		}

        component sub-sub-block { (1a @ 3543)

            component type : AnimationController (0a @ 3545)
            number : 103(10 @ 355a)

            animation controller sub-sub-sub-block { (4aa @ 355d)

                model component : 101(08 @ 355f)
                u1 : 112(10 @ 3561)
                u2 : 1(18 @ 3563)
			}
		}

        component sub-sub-block { (1a @ 3565)

            component type : KeyframeAnimation (0a @ 3567)
            number : 112(10 @ 357a)

            keyframe animation sub-sub-sub-block { (332 @ 357d)

                linked model component number : 101(08 @ 357f)
                name : powershard_sparkle (12 @ 3581)
                u0 : 1(18 @ 3595)
                u1 : 1.0 (25 @ 3597)
                u2 : 1(28 @ 359c)
			}
		}

        component sub-sub-block { (1a @ 359e)

            component type : CollectableItem (0a @ 35a0)
            number : 115(10 @ 35b1)

            collectable item sub-sub-sub-block { (fb2 @ 35b4)

                u0 : 3(08 @ 35b6)
                u1 : 100(10 @ 35b8)

                lua chunk sub-sub-sub-sub-block { (1a @ 35ba)

				}
                name :  (22 @ 35bc)
                ?model :  (2a @ 35be)
                u0 : 0(30 @ 35c0)
			}
		}

        component sub-sub-block { (1a @ 35c2)

            component type : CollisionShape (0a @ 35c4)
            number : 118(10 @ 35d4)

            collision shape sub-sub-sub-block { (3c2 @ 35d7)


                u0 sub-sub-sub-sub-block { (0a @ 35d9)

                    w : -20.0 (0d @ 35db)
                    x : -20.0 (15 @ 35e0)
                    y : 40.0 (1d @ 35e5)
                    z : 40.0 (25 @ 35ea)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 35f0)

                u1 : 1(18 @ 35f2)
                w : -15.0 (35 @ 35f4)
                x : 15.0 (3d @ 35f9)
                y : 3(40 @ 35fe)
                z : 1(58 @ 3600)
			}
		}

        component sub-sub-block { (1a @ 3602)

            component type : SimpleGlow (0a @ 3604)
            number : 120(10 @ 3610)

            simple glow sub-sub-sub-block { (7f2 @ 3613)


                u0 sub-sub-sub-sub-block { (0a @ 3615)

                    w : 0.5000000596046448 (0d @ 3617)
                    x : 1.0 (15 @ 361c)
                    y : 0.3777778148651123 (1d @ 3621)
                    z : 0.5111111402511597 (25 @ 3626)
				}
                u1 : 15.0 (15 @ 362b)
                u2 : 10(18 @ 3630)
                u3 : 15.0 (25 @ 3632)
                u4 : 0.25 (2d @ 3637)
                u5 : 0.800000011920929 (35 @ 363c)

                u6 sub-sub-sub-sub-block { (3a @ 3641)

                    y : 0.0 (0d @ 3643)
                    z : 0.0 (15 @ 3648)
				}
			}
		}

        position sub-sub-block { (22 @ 364d)

            x position : 0.0 (0d @ 364f)
            y position : 0.0 (15 @ 3654)
		}
        z position : 0.0 (2d @ 3659)
        rotation : 0.0 (35 @ 365e)
        scale : 1.0 (3d @ 3663)

        u0 sub-sub-block { (42 @ 3668)

            w : -20.0 (0d @ 366a)
            x : -20.0 (15 @ 366f)
            y : 40.0 (1d @ 3674)
            z : 40.0 (25 @ 3679)
		}
        hidden : 0(48 @ 367e)
	}
    u0 : 0.699999988079071 (15 @ 3680)
}

?item block { (12 @ 3685)


    ?sub-item sub-block { (0a @ 3688)

        name : sshard_blue (12 @ 368b)

        component sub-sub-block { (1a @ 3698)

            component type : PhysicsObject (0a @ 369a)
            number : 1(10 @ 36a9)

            physics object sub-sub-sub-block { (4fa @ 36ac)

                u0 : 1(08 @ 36ae)
                u3 : 1500.0 (25 @ 36b0)
                u4 : 0.0 (2d @ 36b5)
                u5 : 700.0 (35 @ 36ba)
                u6 : 0(38 @ 36bf)
                u7 : 0.0 (45 @ 36c1)
			}
		}

        component sub-sub-block { (1a @ 36c6)

            component type : CollectableItem (0a @ 36c8)
            number : 2(10 @ 36d9)

            collectable item sub-sub-sub-block { (fb2 @ 36dc)

                u0 : 4(08 @ 36de)
                u1 : 1(10 @ 36e0)

                lua chunk sub-sub-sub-sub-block { (1a @ 36e2)

				}
                name :  (22 @ 36e4)
                ?model :  (2a @ 36e6)
                u0 : 0(30 @ 36e8)
			}
		}

        component sub-sub-block { (1a @ 36ea)

            component type : ModelTransformController (0a @ 36ec)
            number : 3(10 @ 3706)

            model transform controller sub-sub-sub-block { (342 @ 3709)

                u0 : 101(08 @ 370b)
                u2 : 4.71238899230957 (2d @ 370d)
			}
		}

        component sub-sub-block { (1a @ 3712)

            component type : Model (0a @ 3714)
            number : 101(10 @ 371b)

            3D model sub-sub-sub-block { (32a @ 371e)

                name : sshard_blue (0a @ 3720)
                u0 : 0.0 (15 @ 372d)
                u1 : 5.0 (1d @ 3732)
                u2 : 0.0 (25 @ 3737)

                u3 sub-sub-sub-sub-block { (2a @ 373c)

                    w : 0.0 (0d @ 373e)
                    x : 0.0 (15 @ 3743)
                    y : 0.0 (1d @ 3748)
                    z : 1.0 (25 @ 374d)
				}

                u4 sub-sub-sub-sub-block { (32 @ 3752)

                    x : 0.0 (0d @ 3754)
                    y : 0.0 (15 @ 3759)
                    z : 0.0 (1d @ 375e)
				}
                u5 : 0(38 @ 3763)

                u6 sub-sub-sub-sub-block { (42 @ 3765)

                    w : 1.0 (0d @ 3767)
                    x : 1.0 (15 @ 376c)
                    y : 1.0 (1d @ 3771)
                    z : 1.0 (25 @ 3776)
				}
			}
		}

        component sub-sub-block { (1a @ 377b)

            component type : SimpleGlow (0a @ 377d)
            number : 102(10 @ 3789)

            simple glow sub-sub-sub-block { (7f2 @ 378c)


                u0 sub-sub-sub-sub-block { (0a @ 378e)

                    w : 0.5 (0d @ 3790)
                    x : 0.5 (15 @ 3795)
                    y : 1.0 (1d @ 379a)
                    z : 0.5 (25 @ 379f)
				}
                u1 : 15.0 (15 @ 37a4)
                u2 : 8(18 @ 37a9)
                u3 : 15.0 (25 @ 37ab)
                u4 : 0.15000000596046448 (2d @ 37b0)
                u5 : 0.800000011920929 (35 @ 37b5)

                u6 sub-sub-sub-sub-block { (3a @ 37ba)

                    y : 0.0 (0d @ 37bc)
                    z : 0.0 (15 @ 37c1)
				}
			}
		}

        component sub-sub-block { (1a @ 37c6)

            component type : CollisionShape (0a @ 37c8)
            number : 105(10 @ 37d8)

            collision shape sub-sub-sub-block { (3c2 @ 37db)


                u0 sub-sub-sub-sub-block { (0a @ 37dd)

                    w : -5.0 (0d @ 37df)
                    x : -15.0 (15 @ 37e4)
                    y : 10.0 (1d @ 37e9)
                    z : 30.0 (25 @ 37ee)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 37f4)

                u1 : 1(18 @ 37f6)
                w : -40.0 (35 @ 37f8)
                x : 40.0 (3d @ 37fd)
                y : 3(40 @ 3802)
                z : 1(58 @ 3804)
			}
		}

        position sub-sub-block { (22 @ 3806)

            x position : 0.0 (0d @ 3808)
            y position : 0.0 (15 @ 380d)
		}
        z position : 0.0 (2d @ 3812)
        rotation : 0.0 (35 @ 3817)
        scale : 1.0 (3d @ 381c)

        u0 sub-sub-block { (42 @ 3821)

            w : -20.0 (0d @ 3823)
            x : -20.0 (15 @ 3828)
            y : 40.0 (1d @ 382d)
            z : 40.0 (25 @ 3832)
		}
        hidden : 0(48 @ 3837)
	}
    u0 : 1.0 (15 @ 3839)
}

?item block { (12 @ 383e)


    ?sub-item sub-block { (0a @ 3841)

        name : sshard_red (12 @ 3844)

        component sub-sub-block { (1a @ 3850)

            component type : PhysicsObject (0a @ 3852)
            number : 1(10 @ 3861)

            physics object sub-sub-sub-block { (4fa @ 3864)

                u0 : 1(08 @ 3866)
                u3 : 1500.0 (25 @ 3868)
                u4 : 0.0 (2d @ 386d)
                u5 : 700.0 (35 @ 3872)
                u6 : 0(38 @ 3877)
                u7 : 0.0 (45 @ 3879)
			}
		}

        component sub-sub-block { (1a @ 387e)

            component type : CollectableItem (0a @ 3880)
            number : 2(10 @ 3891)

            collectable item sub-sub-sub-block { (fb2 @ 3894)

                u0 : 4(08 @ 3896)
                u1 : 5(10 @ 3898)

                lua chunk sub-sub-sub-sub-block { (1a @ 389a)

				}
                name :  (22 @ 389c)
                ?model :  (2a @ 389e)
                u0 : 0(30 @ 38a0)
			}
		}

        component sub-sub-block { (1a @ 38a2)

            component type : ModelTransformController (0a @ 38a4)
            number : 3(10 @ 38be)

            model transform controller sub-sub-sub-block { (342 @ 38c1)

                u0 : 101(08 @ 38c3)
                u2 : 4.71238899230957 (2d @ 38c5)
			}
		}

        component sub-sub-block { (1a @ 38ca)

            component type : Model (0a @ 38cc)
            number : 101(10 @ 38d3)

            3D model sub-sub-sub-block { (32a @ 38d6)

                name : sshard_red (0a @ 38d8)
                u0 : 0.0 (15 @ 38e4)
                u1 : 5.0 (1d @ 38e9)
                u2 : 0.0 (25 @ 38ee)

                u3 sub-sub-sub-sub-block { (2a @ 38f3)

                    w : 0.0 (0d @ 38f5)
                    x : 0.0 (15 @ 38fa)
                    y : 0.0 (1d @ 38ff)
                    z : 1.0 (25 @ 3904)
				}

                u4 sub-sub-sub-sub-block { (32 @ 3909)

                    x : 0.0 (0d @ 390b)
                    y : 0.0 (15 @ 3910)
                    z : 0.0 (1d @ 3915)
				}
                u5 : 0(38 @ 391a)

                u6 sub-sub-sub-sub-block { (42 @ 391c)

                    w : 1.0 (0d @ 391e)
                    x : 1.0 (15 @ 3923)
                    y : 1.0 (1d @ 3928)
                    z : 1.0 (25 @ 392d)
				}
			}
		}

        component sub-sub-block { (1a @ 3932)

            component type : SimpleGlow (0a @ 3934)
            number : 102(10 @ 3940)

            simple glow sub-sub-sub-block { (7f2 @ 3943)


                u0 sub-sub-sub-sub-block { (0a @ 3945)

                    w : 1.0 (0d @ 3947)
                    x : 0.5222222208976746 (15 @ 394c)
                    y : 0.5222222208976746 (1d @ 3951)
                    z : 0.5111111402511597 (25 @ 3956)
				}
                u1 : 15.0 (15 @ 395b)
                u2 : 8(18 @ 3960)
                u3 : 15.0 (25 @ 3962)
                u4 : 0.15000000596046448 (2d @ 3967)
                u5 : 0.800000011920929 (35 @ 396c)

                u6 sub-sub-sub-sub-block { (3a @ 3971)

                    y : 0.0 (0d @ 3973)
                    z : 0.0 (15 @ 3978)
				}
			}
		}

        component sub-sub-block { (1a @ 397d)

            component type : CollisionShape (0a @ 397f)
            number : 105(10 @ 398f)

            collision shape sub-sub-sub-block { (3c2 @ 3992)


                u0 sub-sub-sub-sub-block { (0a @ 3994)

                    w : -5.0 (0d @ 3996)
                    x : -15.0 (15 @ 399b)
                    y : 10.0 (1d @ 39a0)
                    z : 30.0 (25 @ 39a5)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 39ab)

                u1 : 1(18 @ 39ad)
                w : -40.0 (35 @ 39af)
                x : 40.0 (3d @ 39b4)
                y : 3(40 @ 39b9)
                z : 1(58 @ 39bb)
			}
		}

        position sub-sub-block { (22 @ 39bd)

            x position : 0.0 (0d @ 39bf)
            y position : 0.0 (15 @ 39c4)
		}
        z position : 0.0 (2d @ 39c9)
        rotation : 0.0 (35 @ 39ce)
        scale : 1.0 (3d @ 39d3)

        u0 sub-sub-block { (42 @ 39d8)

            w : -15.0 (0d @ 39da)
            x : -15.0 (15 @ 39df)
            y : 30.0 (1d @ 39e4)
            z : 30.0 (25 @ 39e9)
		}
        hidden : 0(48 @ 39ee)
	}
    u0 : 1.0 (15 @ 39f0)
}

?item block { (12 @ 39f5)


    ?sub-item sub-block { (0a @ 39f8)

        name : sshard_yellow (12 @ 39fb)

        component sub-sub-block { (1a @ 3a0a)

            component type : PhysicsObject (0a @ 3a0c)
            number : 1(10 @ 3a1b)

            physics object sub-sub-sub-block { (4fa @ 3a1e)

                u0 : 1(08 @ 3a20)
                u3 : 1500.0 (25 @ 3a22)
                u4 : 0.0 (2d @ 3a27)
                u5 : 700.0 (35 @ 3a2c)
                u6 : 0(38 @ 3a31)
                u7 : 0.0 (45 @ 3a33)
			}
		}

        component sub-sub-block { (1a @ 3a38)

            component type : CollectableItem (0a @ 3a3a)
            number : 2(10 @ 3a4b)

            collectable item sub-sub-sub-block { (fb2 @ 3a4e)

                u0 : 4(08 @ 3a50)
                u1 : 20(10 @ 3a52)

                lua chunk sub-sub-sub-sub-block { (1a @ 3a54)

				}
                name :  (22 @ 3a56)
                ?model :  (2a @ 3a58)
                u0 : 0(30 @ 3a5a)
			}
		}

        component sub-sub-block { (1a @ 3a5c)

            component type : ModelTransformController (0a @ 3a5e)
            number : 3(10 @ 3a78)

            model transform controller sub-sub-sub-block { (342 @ 3a7b)

                u0 : 101(08 @ 3a7d)
                u2 : 4.71238899230957 (2d @ 3a7f)
			}
		}

        component sub-sub-block { (1a @ 3a84)

            component type : Model (0a @ 3a86)
            number : 101(10 @ 3a8d)

            3D model sub-sub-sub-block { (32a @ 3a90)

                name : sshard_yellow (0a @ 3a92)
                u0 : 0.0 (15 @ 3aa1)
                u1 : 5.0 (1d @ 3aa6)
                u2 : 0.0 (25 @ 3aab)

                u3 sub-sub-sub-sub-block { (2a @ 3ab0)

                    w : 0.0 (0d @ 3ab2)
                    x : 0.0 (15 @ 3ab7)
                    y : 0.0 (1d @ 3abc)
                    z : 1.0 (25 @ 3ac1)
				}

                u4 sub-sub-sub-sub-block { (32 @ 3ac6)

                    x : 0.0 (0d @ 3ac8)
                    y : 0.0 (15 @ 3acd)
                    z : 0.0 (1d @ 3ad2)
				}
                u5 : 0(38 @ 3ad7)

                u6 sub-sub-sub-sub-block { (42 @ 3ad9)

                    w : 1.0 (0d @ 3adb)
                    x : 1.0 (15 @ 3ae0)
                    y : 1.0 (1d @ 3ae5)
                    z : 1.0 (25 @ 3aea)
				}
			}
		}

        component sub-sub-block { (1a @ 3aef)

            component type : SimpleGlow (0a @ 3af1)
            number : 102(10 @ 3afd)

            simple glow sub-sub-sub-block { (7f2 @ 3b00)


                u0 sub-sub-sub-sub-block { (0a @ 3b02)

                    w : 0.7444446086883545 (0d @ 3b04)
                    x : 0.7444444894790649 (15 @ 3b09)
                    y : 0.0 (1d @ 3b0e)
                    z : 0.18888893723487854 (25 @ 3b13)
				}
                u1 : 15.0 (15 @ 3b18)
                u2 : 8(18 @ 3b1d)
                u3 : 15.0 (25 @ 3b1f)
                u4 : 0.15000000596046448 (2d @ 3b24)
                u5 : 0.800000011920929 (35 @ 3b29)

                u6 sub-sub-sub-sub-block { (3a @ 3b2e)

                    y : 0.0 (0d @ 3b30)
                    z : 0.0 (15 @ 3b35)
				}
			}
		}

        component sub-sub-block { (1a @ 3b3a)

            component type : CollisionShape (0a @ 3b3c)
            number : 105(10 @ 3b4c)

            collision shape sub-sub-sub-block { (3c2 @ 3b4f)


                u0 sub-sub-sub-sub-block { (0a @ 3b51)

                    w : -5.0 (0d @ 3b53)
                    x : -15.0 (15 @ 3b58)
                    y : 10.0 (1d @ 3b5d)
                    z : 30.0 (25 @ 3b62)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 3b68)

                u1 : 1(18 @ 3b6a)
                w : -40.0 (35 @ 3b6c)
                x : 40.0 (3d @ 3b71)
                y : 3(40 @ 3b76)
                z : 1(58 @ 3b78)
			}
		}

        position sub-sub-block { (22 @ 3b7a)

            x position : 0.0 (0d @ 3b7c)
            y position : 0.0 (15 @ 3b81)
		}
        z position : 0.0 (2d @ 3b86)
        rotation : 0.0 (35 @ 3b8b)
        scale : 1.0 (3d @ 3b90)

        u0 sub-sub-block { (42 @ 3b95)

            w : -15.0 (0d @ 3b97)
            x : -15.0 (15 @ 3b9c)
            y : 30.0 (1d @ 3ba1)
            z : 30.0 (25 @ 3ba6)
		}
        hidden : 0(48 @ 3bab)
	}
    u0 : 1.0 (15 @ 3bad)
}

?item block { (12 @ 3bb2)


    ?sub-item sub-block { (0a @ 3bb5)

        name : xp_sack (12 @ 3bb8)

        component sub-sub-block { (1a @ 3bc1)

            component type : Model (0a @ 3bc3)
            number : 101(10 @ 3bca)

            3D model sub-sub-sub-block { (32a @ 3bcd)

                name : xp_sack (0a @ 3bcf)
                u0 : 1.5707963705062866 (15 @ 3bd8)
                u1 : 0.5 (1d @ 3bdd)
                u2 : 0.0 (25 @ 3be2)

                u3 sub-sub-sub-sub-block { (2a @ 3be7)

                    w : 1.0 (0d @ 3be9)
                    x : 1.0 (15 @ 3bee)
                    y : 1.0 (1d @ 3bf3)
                    z : 1.0 (25 @ 3bf8)
				}

                u4 sub-sub-sub-sub-block { (32 @ 3bfd)

                    x : 0.0 (0d @ 3bff)
                    y : 0.0 (15 @ 3c04)
                    z : 0.0 (1d @ 3c09)
				}
                u5 : 0(38 @ 3c0e)

                u6 sub-sub-sub-sub-block { (42 @ 3c10)

                    w : 1.0 (0d @ 3c12)
                    x : 1.0 (15 @ 3c17)
                    y : 1.0 (1d @ 3c1c)
                    z : 1.0 (25 @ 3c21)
				}
			}
		}

        component sub-sub-block { (1a @ 3c26)

            component type : ParticleEmitter (0a @ 3c29)
            number : 102(10 @ 3c3a)

            particle emitter sub-sub-sub-block { (7d2 @ 3c3d)

                particle : 103(10 @ 3c40)
                particle : 106(10 @ 3c42)
                u1 : 0(18 @ 3c44)
                u2 : 80(20 @ 3c46)
                u3 : 0(28 @ 3c48)
                u4 : 0(30 @ 3c4a)

                u5 sub-sub-sub-sub-block { (3a @ 3c4c)

                    u0 : 5(08 @ 3c4f)

                    u1 sub-sub-sub-sub-sub-block { (12 @ 3c51)

                        w : 1.0 (0d @ 3c53)
                        x : 1.0 (15 @ 3c58)
                        y : 1.0 (1d @ 3c5d)
                        z : 0.0 (25 @ 3c62)
					}
                    u2 : 90.0 (1d @ 3c67)
                    u2 : 45.0 (1d @ 3c6c)
                    u2 : 0.0 (1d @ 3c71)
                    u2 : 15.0 (1d @ 3c76)
                    u2 : 0.0 (1d @ 3c7b)
                    u2 : 0.0 (1d @ 3c80)
                    u2 : 0.0 (1d @ 3c85)
                    u2 : 0.0 (1d @ 3c8a)
                    u2 : 1.0 (1d @ 3c8f)
                    u2 : 0.0 (1d @ 3c94)
                    u2 : 1.0 (1d @ 3c99)
                    u2 : 0.05000000074505806 (1d @ 3c9e)
                    u2 : 1.5 (1d @ 3ca3)
                    u2 : 0.0 (1d @ 3ca8)
                    u2 : 0.0 (1d @ 3cad)
                    u3 : 0.0 (25 @ 3cb2)
                    u4 : 0.0 (2d @ 3cb7)
                    u5 : 0.0 (35 @ 3cbc)

                    u6 sub-sub-sub-sub-sub-block { (3a @ 3cc1)

                        u0 : 0.0 (0d @ 3cc3)
                        u1 : 80.0 (15 @ 3cc8)
                        u2 : 0.0 (1d @ 3ccd)
					}
				}
                u6 : 0(40 @ 3cd2)

                u7 sub-sub-sub-sub-block { (4a @ 3cd4)

                    u0 : 0.0 (0d @ 3cd6)
                    u1 : 20.0 (15 @ 3cdb)
                    u2 : 0.0 (1d @ 3ce0)
				}
			}
		}

        component sub-sub-block { (1a @ 3ce5)

            component type : Particle (0a @ 3ce7)
            number : 103(10 @ 3cf1)

            particle sub-sub-sub-block { (7da @ 3cf4)

                name : particle_fure_1 (0a @ 3cf6)
                u0 : 4.0 (15 @ 3d07)
			}
		}

        component sub-sub-block { (1a @ 3d0c)

            component type : SimpleGlow (0a @ 3d0e)
            number : 104(10 @ 3d1a)

            simple glow sub-sub-sub-block { (7f2 @ 3d1d)


                u0 sub-sub-sub-sub-block { (0a @ 3d1f)

                    w : 0.5666666626930237 (0d @ 3d21)
                    x : 0.46666666865348816 (15 @ 3d26)
                    y : 0.0 (1d @ 3d2b)
                    z : 0.5 (25 @ 3d30)
				}
                u1 : 80.0 (15 @ 3d35)
                u2 : 20(18 @ 3d3a)
                u3 : 0.0 (25 @ 3d3c)
                u4 : 0.15000000596046448 (2d @ 3d41)
                u5 : 0.800000011920929 (35 @ 3d46)

                u6 sub-sub-sub-sub-block { (3a @ 3d4b)

                    y : 0.0 (0d @ 3d4d)
                    z : 50.0 (15 @ 3d52)
				}
			}
		}

        component sub-sub-block { (1a @ 3d57)

            component type : Particle (0a @ 3d59)
            number : 106(10 @ 3d63)

            particle sub-sub-sub-block { (7da @ 3d66)

                name : particle_fure_2 (0a @ 3d68)
                u0 : 8.0 (15 @ 3d79)
			}
		}

        component sub-sub-block { (1a @ 3d7e)

            component type : PhysicsObject (0a @ 3d80)
            number : 108(10 @ 3d8f)

            physics object sub-sub-sub-block { (4fa @ 3d92)

                u0 : 1(08 @ 3d94)
                u2 : 0.800000011920929 (1d @ 3d96)
                u3 : 1500.0 (25 @ 3d9b)
                u4 : 0.0 (2d @ 3da0)
                u5 : 700.0 (35 @ 3da5)
                u6 : 0(38 @ 3daa)
                u7 : 0.0 (45 @ 3dac)
			}
		}

        component sub-sub-block { (1a @ 3db1)

            component type : CollectableItem (0a @ 3db3)
            number : 110(10 @ 3dc4)

            collectable item sub-sub-sub-block { (fb2 @ 3dc7)

                u0 : 0(08 @ 3dc9)
                u1 : 0(10 @ 3dcb)

                lua chunk sub-sub-sub-sub-block { (1a @ 3dcd)

				}
                name :  (22 @ 3dcf)
                ?model : experiencesack (2a @ 3dd1)
                u0 : 1(30 @ 3de1)
			}
		}

        component sub-sub-block { (1a @ 3de3)

            component type : CollisionShape (0a @ 3de5)
            number : 111(10 @ 3df5)

            collision shape sub-sub-sub-block { (3c2 @ 3df8)


                u0 sub-sub-sub-sub-block { (0a @ 3dfa)

                    w : -50.0 (0d @ 3dfc)
                    x : 0.0 (15 @ 3e01)
                    y : 100.0 (1d @ 3e06)
                    z : 106.42947387695312 (25 @ 3e0b)
				}
			}

            collision shape 2 sub-sub-sub-block { (3ca @ 3e11)

                u1 : 1(18 @ 3e13)
                w : -40.0 (35 @ 3e15)
                x : 40.0 (3d @ 3e1a)
                y : 3(40 @ 3e1f)
                z : 1(58 @ 3e21)
			}
		}

        component sub-sub-block { (1a @ 3e23)

            component type : ModelTransformController (0a @ 3e25)
            number : 113(10 @ 3e3f)

            model transform controller sub-sub-sub-block { (342 @ 3e42)

                u0 : 101(08 @ 3e44)
			}
		}

        position sub-sub-block { (22 @ 3e46)

            x position : 0.0 (0d @ 3e48)
            y position : 0.0 (15 @ 3e4d)
		}
        z position : 0.0 (2d @ 3e52)
        rotation : 0.0 (35 @ 3e57)
        scale : 1.0 (3d @ 3e5c)

        u0 sub-sub-block { (42 @ 3e61)

            w : -80.0 (0d @ 3e63)
            x : -80.0 (15 @ 3e68)
            y : 160.0 (1d @ 3e6d)
            z : 186.42947387695312 (25 @ 3e72)
		}
        hidden : 0(48 @ 3e77)
	}
    u0 : 0.4000000059604645 (15 @ 3e79)
}
